/*2021-01-13三科定制*/
SET DATEFIRST 1
DECLARE @now Date =GetDate()
declare @yesterday Date =DATEADD(day, -1, @now)
declare @weekstartday Date =DATEADD(day, 1 - datepart(weekday, @now), @now)
declare @weekendday Date =DATEADD(day, -1, DATEADD(week, 1, @weekstartday))
declare @monthstartday Date =DATEADD(day, 1 - day(@now), @now)
declare @monthendday Date =DATEADD(day, -1, DATEADD(month, 1, @monthstartday))
declare @yearstartday Date =cast(year(@now) as varchar(4)) + '-01-01';
declare @yearendday Date =DATEADD(day, -1, DATEADD(year, 1, @yearstartday))
declare @quarterstartday Date =DATEADD(month, (datepart(quarter, @now) - 1) * 3, @yearstartday)
declare @quarterendday Date =DATEADD(day, -1, DATEADD(quarter, 1, @quarterstartday))

DECLARE @jtGuid UNIQUEIDENTIFIER;
SET @jtGuid = '11B11DB4-E907-4F1F-8835-B9DAAB6E1F23';

with [bu] AS (
	select BUGUID, BUName, HierarchyCode from data_wide_mdm_BusinessUnit WITH (NOLOCK) WHERE IsEndCompany = 1
),
	 [proj] as (
		 select proj.p_projectId     as projGuid,
				parent.p_projectId   as parentGuid,
				proj.ProjName        as ProjName,
				parent.ProjName      as ParentProjName,
				proj.BUGUID,
				proj.HierarchyCode,
				parent.HierarchyCode as ParentHierarchyCode
		 from data_wide_mdm_Project proj with (nolock)
				  left join data_wide_mdm_Project parent on proj.ParentGUID = parent.p_projectId
		 where proj.IfEnd =1
		   and proj.ApplySys like '%0011%'
	 ),
	 -- 累计实际回款
	 [ActualGetIn] as (
		 SELECT
			 /* 昨日回款 */
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @yesterday and TopProductTypeName='车库/库房'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_车位昨日],
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @yesterday and TopProductTypeName='住宅'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_住宅昨日],
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @yesterday and TopProductTypeName='商业'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_商业昨日],

			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then LoanHousingAmount else 0 end, 0)), 0)                           AS [贷款类回款金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then NonLoanHousingAmount else 0 end, 0)), 0)                        AS [非贷款类回款金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then SupplementaryAgreementAmount else 0 end, 0)), 0)                AS [补充协议款_昨日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then HousingAmount else 0 end, 0)), 0)                               AS [回款金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then Report_BuildAmount else 0 end, 0)), 0)                          AS [楼款_模糊匹配_昨日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then Report_FirstAmount else 0 end, 0)), 0)                          AS [首期_模糊匹配_昨日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then Report_EarnestAmount else 0 end, 0)), 0)                        AS [定金_模糊匹配_昨日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @yesterday then Report_OtherAmount else 0 end, 0)), 0)                          AS [其他_模糊匹配_昨日],
			 /* 本日回款 */
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @now and TopProductTypeName='车库/库房'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_车位本日],
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @now and TopProductTypeName='住宅'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_住宅本日],
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @now and TopProductTypeName='商业'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_商业本日],

			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @now then LoanHousingAmount else 0 end,  0)), 0)                                AS [贷款类回款金额_本日],
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @now then NonLoanHousingAmount else 0 end, 0)), 0)                              AS [非贷款类回款金额_本日],
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @now then SupplementaryAgreementAmount else 0 end, 0)), 0)                      AS [补充协议款_本日],
			 isnull(SUM(ISNULL(case when Cast(StatisticalDate as Date) = @now then HousingAmount else 0 end,  0)), 0)                                   AS [回款金额_本日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @now then Report_BuildAmount else 0 end, 0)), 0)                              AS [楼款_模糊匹配_本日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @now then Report_FirstAmount else 0 end, 0)), 0)                              AS [首期_模糊匹配_本日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @now then Report_EarnestAmount else 0 end, 0)), 0)                            AS [定金_模糊匹配_本日],
			 isnull(SUM(ISNULL(case when  Cast(StatisticalDate as Date) = @now then Report_OtherAmount else 0 end, 0)), 0)                              AS [其他_模糊匹配_本日],
			 /* 本周回款 */
			 isnull(SUM(ISNULL(case when (StatisticalDate between @weekstartday and @weekendday) and TopProductTypeName='车库/库房'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_车位本周],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @weekstartday and @weekendday) and TopProductTypeName='住宅'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_住宅本周],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @weekstartday and @weekendday) and TopProductTypeName='商业'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_商业本周],

			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday  then LoanHousingAmount else 0 end, 0)), 0)                AS [贷款类回款金额_本周],
			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday  then NonLoanHousingAmount  else 0 end, 0)), 0)            AS [非贷款类回款金额_本周],
			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday then SupplementaryAgreementAmount  else 0 end, 0)), 0)    AS [补充协议款_本周],
			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday then HousingAmount  else 0 end, 0)), 0)                   AS [回款金额_本周],
			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday then Report_BuildAmount else 0 end, 0)), 0)                AS [楼款_模糊匹配_本周],
			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday then Report_FirstAmount else 0 end, 0)), 0)                AS [首期_模糊匹配_本周],
			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday then Report_EarnestAmount else 0 end, 0)), 0)              AS [定金_模糊匹配_本周],
			 isnull(SUM(ISNULL(case when StatisticalDate between @weekstartday and @weekendday then Report_OtherAmount else 0 end, 0)), 0)                AS [其他_模糊匹配_本周],
			 /* 本月回款 */
			 isnull(SUM(ISNULL(case when (StatisticalDate between @monthstartday and @monthendday) and TopProductTypeName='车库/库房'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_车位本月],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @monthstartday and @monthendday) and TopProductTypeName='住宅'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_住宅本月],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @monthstartday and @monthendday) and TopProductTypeName='商业'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_商业本月],

			 isnull(SUM(ISNULL(case when  StatisticalDate between @monthstartday and @monthendday then LoanHousingAmount else 0 end, 0)), 0)              AS [贷款类回款金额_本月],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @monthstartday and @monthendday then NonLoanHousingAmount else 0 end, 0)), 0)           AS [非贷款类回款金额_本月],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @monthstartday and @monthendday then SupplementaryAgreementAmount else 0 end, 0)), 0)   AS [补充协议款_本月],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @monthstartday and @monthendday then HousingAmount else 0 end, 0)), 0)                  AS [回款金额_本月],
			 isnull(SUM(ISNULL(case when StatisticalDate between @monthstartday and @monthendday then Report_BuildAmount else 0 end, 0)), 0)                AS [楼款_模糊匹配_本月],
			 isnull(SUM(ISNULL(case when StatisticalDate between @monthstartday and @monthendday then Report_FirstAmount else 0 end, 0)), 0)                AS [首期_模糊匹配_本月],
			 isnull(SUM(ISNULL(case when StatisticalDate between @monthstartday and @monthendday then Report_EarnestAmount else 0 end, 0)), 0)              AS [定金_模糊匹配_本月],
			 isnull(SUM(ISNULL(case when StatisticalDate between @monthstartday and @monthendday then Report_OtherAmount else 0 end, 0)), 0)                AS [其他_模糊匹配_本月],
			 /* 本季回款 */
			 isnull(SUM(ISNULL(case when (StatisticalDate between @quarterstartday and @quarterendday) and TopProductTypeName='车库/库房'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_车位本季],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @quarterstartday and @quarterendday) and TopProductTypeName='住宅'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_住宅本季],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @quarterstartday and @quarterendday) and TopProductTypeName='商业'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_商业本季],

			 isnull(SUM(ISNULL(case when  StatisticalDate between @quarterstartday and @quarterendday then LoanHousingAmount else 0 end, 0)), 0)             AS [贷款类回款金额_本季],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @quarterstartday and @quarterendday then NonLoanHousingAmount else 0 end, 0)), 0)          AS [非贷款类回款金额_本季],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @quarterstartday and @quarterendday then SupplementaryAgreementAmount else 0 end, 0)), 0)  AS [补充协议款_本季],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @quarterstartday and @quarterendday then HousingAmount else 0 end, 0)), 0)                 AS [回款金额_本季],
			 isnull(SUM(ISNULL(case when StatisticalDate between @quarterstartday and @quarterendday then Report_BuildAmount else 0 end, 0)), 0)                AS [楼款_模糊匹配_本季],
			 isnull(SUM(ISNULL(case when StatisticalDate between @quarterstartday and @quarterendday then Report_FirstAmount else 0 end, 0)), 0)                AS [首期_模糊匹配_本季],
			 isnull(SUM(ISNULL(case when StatisticalDate between @quarterstartday and @quarterendday then Report_EarnestAmount else 0 end, 0)), 0)              AS [定金_模糊匹配_本季],
			 isnull(SUM(ISNULL(case when StatisticalDate between @quarterstartday and @quarterendday then Report_OtherAmount else 0 end, 0)), 0)                AS [其他_模糊匹配_本季],
			 /* 本年回款 */
			 isnull(SUM(ISNULL(case when (StatisticalDate between @yearstartday and @yearendday) and TopProductTypeName='车库/库房'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_车位本年],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @yearstartday and @yearendday) and TopProductTypeName='住宅'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_住宅本年],
			 isnull(SUM(ISNULL(case when (StatisticalDate between @yearstartday and @yearendday) and TopProductTypeName='商业'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_商业本年],

			 isnull(SUM(ISNULL(case when  StatisticalDate between @yearstartday and @yearendday then LoanHousingAmount else 0 end, 0)), 0)                AS [贷款类回款金额_本年],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @yearstartday and @yearendday then NonLoanHousingAmount else 0 end, 0)), 0)             AS [非贷款类回款金额_本年],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @yearstartday and @yearendday then SupplementaryAgreementAmount else 0 end, 0)), 0)     AS [补充协议款_本年],
			 isnull(SUM(ISNULL(case when  StatisticalDate between @yearstartday and @yearendday then HousingAmount else 0 end, 0)), 0)                    AS [回款金额_本年],
			 isnull(SUM(ISNULL(case when StatisticalDate between @yearstartday and @yearendday then Report_BuildAmount else 0 end, 0)), 0)                AS [楼款_模糊匹配_本年],
			 isnull(SUM(ISNULL(case when StatisticalDate between @yearstartday and @yearendday then Report_FirstAmount else 0 end, 0)), 0)                AS [首期_模糊匹配_本年],
			 isnull(SUM(ISNULL(case when StatisticalDate between @yearstartday and @yearendday then Report_EarnestAmount else 0 end, 0)), 0)              AS [定金_模糊匹配_本年],
			 isnull(SUM(ISNULL(case when StatisticalDate between @yearstartday and @yearendday then Report_OtherAmount else 0 end, 0)), 0)                AS [其他_模糊匹配_本年],
			 /* 累计回款 */
			 isnull(SUM(ISNULL(case when TopProductTypeName='车库/库房'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_车位累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='住宅'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_住宅累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='商业'  then  HousingAmount else 0 end, 0)), 0)   AS [回款金额_商业累计],

			 isnull(SUM(ISNULL(LoanHousingAmount, 0)), 0)            AS [贷款类回款金额_累计],
			 isnull(SUM(ISNULL(NonLoanHousingAmount, 0)), 0)         AS [非贷款类回款金额_累计],
			 isnull(SUM(ISNULL(SupplementaryAgreementAmount, 0)), 0) AS [补充协议款_累计],
			 isnull(SUM(ISNULL(HousingAmount, 0)), 0)                AS [回款金额_累计],
			 isnull(SUM(ISNULL(Report_BuildAmount, 0)), 0)           AS [楼款_模糊匹配_累计],
			 isnull(SUM(ISNULL(Report_FirstAmount, 0)), 0)           AS [首期_模糊匹配_累计],
			 isnull(SUM(ISNULL(Report_EarnestAmount, 0)), 0)         AS [定金_模糊匹配_累计],
			 isnull(SUM(ISNULL(Report_OtherAmount, 0)), 0)           AS [其他_模糊匹配_累计],
			 ProjGUID,
			 ProjName,
			 ParentProjName,
			 ParentProjGUID,
			 BUGUID,
			 BUName
		 from (
				  SELECT LoanHousingAmount,
						 NonLoanHousingAmount,
						 HousingAmount,
						 SupplementaryAgreementAmount,
						 Report_BuildAmount,
						 Report_FirstAmount,
						 Report_EarnestAmount,
						 Report_OtherAmount,
						 StatisticalDate,
						 ProjGUID,
						 ProjName,
						 ParentProjName,
						 ParentProjGUID,
						 TopProductTypeName,
						 BUGUID,
						 BUName
				  FROM dbo.data_wide_dws_s_Return WITH (NOLOCK)
			  ) A
		 group by
			 ProjGUID,
			 ProjName,
			 ParentProjName,
			 ParentProjGUID,
			 BUGUID,
			 BUName
	 ),
	 -- 累计实际签约
	 [ActualContract] as (
		 SELECT
		 /*三科需求*/
			  isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='车库/库房' and ActualCAmount=0 then  ts else 0 end, 0)), 0)   AS [签约套数_赠送车位昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @now) and TopProductTypeName='车库/库房' and ActualCAmount=0 then  ts else 0 end, 0)), 0)   AS [签约套数_赠送车位本日],
			  isnull(SUM(ISNULL(case when ( HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='车库/库房' and ActualCAmount=0 then  ts else 0 end, 0)), 0)   AS [签约套数_赠送车位本周],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='车库/库房' and ActualCAmount=0 then  ts else 0 end, 0)), 0)   AS [签约套数_赠送车位本月],
			  isnull(SUM(ISNULL(case when ( HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='车库/库房' and ActualCAmount=0 then  ts else 0 end, 0)), 0)   AS [签约套数_赠送车位本季],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='车库/库房' and ActualCAmount=0 then  ts else 0 end, 0)), 0)   AS [签约套数_赠送车位本年],
			 isnull(SUM(ISNULL(case when  TopProductTypeName='车库/库房' and ActualCAmount=0 then  ts else 0 end, 0)), 0)   AS [签约套数_赠送车位累计],

		 /* 昨日签约 */
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='车库/库房' and ActualCAmount<>0  then  ts else 0 end, 0)), 0)   AS [签约套数_车位昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [签约套数_住宅昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [签约套数_商业昨日],

			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='车库/库房'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_车位昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='住宅'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_住宅昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='商业'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_商业昨日],

			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualCAmount else 0 end , 0)), 0)            AS [签约金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualMainRoomCAmount else 0 end , 0)), 0)    AS [主房间签约金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualAttachRoomCAmount else 0 end , 0)), 0)  AS [附属房间签约金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualMainRoomCBldArea else 0 end , 0)), 0)   AS [主房间签约面积_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualAttachRoomCBldArea else 0 end , 0)), 0) AS [附属房间签约面积_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualMainRoomCTs else 0 end , 0)), 0)        AS [主房间签约套数_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualAttachRoomCTs else 0 end , 0)), 0)      AS [附属房间签约套数_昨日],
			 /* 本日签约 */
			 isnull(SUM(ISNULL(case when (Cast(HsTjDate as Date) = @now) and TopProductTypeName='车库/库房'  and ActualCAmount<>0 then  ts else 0 end, 0)), 0)   AS [签约套数_车位本日],
			 isnull(SUM(ISNULL(case when (Cast(HsTjDate as Date) = @now) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [签约套数_住宅本日],
			 isnull(SUM(ISNULL(case when (Cast(HsTjDate as Date) = @now) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [签约套数_商业本日],

			 isnull(SUM(ISNULL(case when (Cast(HsTjDate as Date) = @now) and TopProductTypeName='车库/库房'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_车位本日],
			 isnull(SUM(ISNULL(case when (Cast(HsTjDate as Date) = @now) and TopProductTypeName='住宅'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_住宅本日],
			 isnull(SUM(ISNULL(case when (Cast(HsTjDate as Date) = @now) and TopProductTypeName='商业'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_商业本日],

			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualCAmount else 0 end , 0)), 0)            AS [签约金额_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualMainRoomCAmount else 0 end , 0)), 0)    AS [主房间签约金额_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualAttachRoomCAmount else 0 end , 0)), 0)  AS [附属房间签约金额_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualMainRoomCBldArea else 0 end , 0)), 0)   AS [主房间签约面积_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualAttachRoomCBldArea else 0 end , 0)), 0) AS [附属房间签约面积_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualMainRoomCTs else 0 end , 0)), 0)        AS [主房间签约套数_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualAttachRoomCTs else 0 end , 0)), 0)      AS [附属房间签约套数_本日],
			 /* 本周签约 */
			 isnull(SUM(ISNULL(case when (HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='车库/库房'  and ActualCAmount<>0 then  ts else 0 end, 0)), 0)   AS [签约套数_车位本周],
			 isnull(SUM(ISNULL(case when (HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='住宅'  then ts else 0 end, 0)), 0)   AS [签约套数_住宅本周],
			 isnull(SUM(ISNULL(case when (HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [签约套数_商业本周],

			 isnull(SUM(ISNULL(case when (HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='车库/库房'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_车位本周],
			 isnull(SUM(ISNULL(case when (HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='住宅'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_住宅本周],
			 isnull(SUM(ISNULL(case when (HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='商业'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_商业本周],

			 isnull(SUM(ISNULL(case when HsTjDate between @weekstartday and @weekendday then ActualCAmount else 0 end , 0)), 0)            AS [签约金额_本周],
			 isnull(SUM(ISNULL(case when HsTjDate between @weekstartday and @weekendday then ActualMainRoomCAmount else 0 end , 0)), 0)    AS [主房间签约金额_本周],
			 isnull(SUM(ISNULL(case when HsTjDate between @weekstartday and @weekendday then ActualAttachRoomCAmount else 0 end , 0)), 0)  AS [附属房间签约金额_本周],
			 isnull(SUM(ISNULL(case when HsTjDate between @weekstartday and @weekendday then ActualMainRoomCBldArea else 0 end , 0)), 0)   AS [主房间签约面积_本周],
			 isnull(SUM(ISNULL(case when HsTjDate between @weekstartday and @weekendday then ActualAttachRoomCBldArea else 0 end , 0)), 0) AS [附属房间签约面积_本周],
			 isnull(SUM(ISNULL(case when HsTjDate between @weekstartday and @weekendday then ActualMainRoomCTs else 0 end , 0)), 0)        AS [主房间签约套数_本周],
			 isnull(SUM(ISNULL(case when HsTjDate between @weekstartday and @weekendday then ActualAttachRoomCTs else 0 end , 0)), 0)      AS [附属房间签约套数_本周],
			 /* 本月签约 */
			 isnull(SUM(ISNULL(case when (HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='车库/库房'  and ActualCAmount<>0 then  ts else 0 end, 0)), 0)   AS [签约套数_车位本月],
			 isnull(SUM(ISNULL(case when (HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [签约套数_住宅本月],
			 isnull(SUM(ISNULL(case when (HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [签约套数_商业本月],

			 isnull(SUM(ISNULL(case when (HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='车库/库房'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_车位本月],
			 isnull(SUM(ISNULL(case when (HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='住宅'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_住宅本月],
			 isnull(SUM(ISNULL(case when (HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='商业'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_商业本月],

			 isnull(SUM(ISNULL(case when HsTjDate between @monthstartday and @monthendday then ActualCAmount else 0 end , 0)), 0)            AS [签约金额_本月],
			 isnull(SUM(ISNULL(case when HsTjDate between @monthstartday and @monthendday then ActualMainRoomCAmount else 0 end , 0)), 0)    AS [主房间签约金额_本月],
			 isnull(SUM(ISNULL(case when HsTjDate between @monthstartday and @monthendday then ActualAttachRoomCAmount else 0 end , 0)), 0)  AS [附属房间签约金额_本月],
			 isnull(SUM(ISNULL(case when HsTjDate between @monthstartday and @monthendday then ActualMainRoomCBldArea else 0 end , 0)), 0)   AS [主房间签约面积_本月],
			 isnull(SUM(ISNULL(case when HsTjDate between @monthstartday and @monthendday then ActualAttachRoomCBldArea else 0 end , 0)), 0) AS [附属房间签约面积_本月],
			 isnull(SUM(ISNULL(case when HsTjDate between @monthstartday and @monthendday then ActualMainRoomCTs else 0 end , 0)), 0)        AS [主房间签约套数_本月],
			 isnull(SUM(ISNULL(case when HsTjDate between @monthstartday and @monthendday then ActualAttachRoomCTs else 0 end , 0)), 0)      AS [附属房间签约套数_本月],
			 /* 本季签约 */
			 isnull(SUM(ISNULL(case when (HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='车库/库房'  and ActualCAmount<>0  then ts else 0 end, 0)), 0)   AS [签约套数_车位本季],
			 isnull(SUM(ISNULL(case when (HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [签约套数_住宅本季],
			 isnull(SUM(ISNULL(case when (HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [签约套数_商业本季],

			 isnull(SUM(ISNULL(case when (HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='车库/库房'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_车位本季],
			 isnull(SUM(ISNULL(case when (HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='住宅'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_住宅本季],
			 isnull(SUM(ISNULL(case when (HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='商业'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_商业本季],

			 isnull(SUM(ISNULL(case when HsTjDate between @quarterstartday and @quarterendday then ActualCAmount else 0 end , 0)), 0)            AS [签约金额_本季],
			 isnull(SUM(ISNULL(case when HsTjDate between @quarterstartday and @quarterendday then ActualMainRoomCAmount else 0 end , 0)), 0)    AS [主房间签约金额_本季],
			 isnull(SUM(ISNULL(case when HsTjDate between @quarterstartday and @quarterendday then ActualAttachRoomCAmount else 0 end , 0)), 0)  AS [附属房间签约金额_本季],
			 isnull(SUM(ISNULL(case when HsTjDate between @quarterstartday and @quarterendday then ActualMainRoomCBldArea else 0 end , 0)), 0)   AS [主房间签约面积_本季],
			 isnull(SUM(ISNULL(case when HsTjDate between @quarterstartday and @quarterendday then ActualAttachRoomCBldArea else 0 end , 0)), 0) AS [附属房间签约面积_本季],
			 isnull(SUM(ISNULL(case when HsTjDate between @quarterstartday and @quarterendday then ActualMainRoomCTs else 0 end , 0)), 0)        AS [主房间签约套数_本季],
			 isnull(SUM(ISNULL(case when HsTjDate between @quarterstartday and @quarterendday then ActualAttachRoomCTs else 0 end , 0)), 0)      AS [附属房间签约套数_本季],
			 /* 本年签约 */
			 isnull(SUM(ISNULL(case when (HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='车库/库房'  and ActualCAmount<>0  then  ts else 0 end, 0)), 0)   AS [签约套数_车位本年],
			 isnull(SUM(ISNULL(case when (HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [签约套数_住宅本年],
			 isnull(SUM(ISNULL(case when (HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [签约套数_商业本年],

			 isnull(SUM(ISNULL(case when (HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='车库/库房'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_车位本年],
			 isnull(SUM(ISNULL(case when (HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='住宅'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_住宅本年],
			 isnull(SUM(ISNULL(case when (HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='商业'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_商业本年],
			 isnull(SUM(ISNULL(case when HsTjDate between @yearstartday and @yearendday then ActualCAmount else 0 end , 0)), 0)            AS [签约金额_本年],
			 isnull(SUM(ISNULL(case when HsTjDate between @yearstartday and @yearendday then ActualMainRoomCAmount else 0 end , 0)), 0)    AS [主房间签约金额_本年],
			 isnull(SUM(ISNULL(case when HsTjDate between @yearstartday and @yearendday then ActualAttachRoomCAmount else 0 end , 0)), 0)  AS [附属房间签约金额_本年],
			 isnull(SUM(ISNULL(case when HsTjDate between @yearstartday and @yearendday then ActualMainRoomCBldArea else 0 end , 0)), 0)   AS [主房间签约面积_本年],
			 isnull(SUM(ISNULL(case when HsTjDate between @yearstartday and @yearendday then ActualAttachRoomCBldArea else 0 end , 0)), 0) AS [附属房间签约面积_本年],
			 isnull(SUM(ISNULL(case when HsTjDate between @yearstartday and @yearendday then ActualMainRoomCTs else 0 end , 0)), 0)        AS [主房间签约套数_本年],
			 isnull(SUM(ISNULL(case when HsTjDate between @yearstartday and @yearendday then ActualAttachRoomCTs else 0 end , 0)), 0)      AS [附属房间签约套数_本年],
			 /* 累计签约 */
			 isnull(SUM(ISNULL(case when TopProductTypeName='车库/库房'   and ActualCAmount<>0 then  ts else 0 end, 0)), 0)   AS [签约套数_车位累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [签约套数_住宅累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [签约套数_商业累计],

			 isnull(SUM(ISNULL(case when TopProductTypeName='车库/库房'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_车位累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='住宅'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_住宅累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='商业'  then  ActualCAmount else 0 end, 0)), 0)   AS [签约金额_商业累计],
			 isnull(SUM(ISNULL(ActualCAmount, 0)), 0)            AS [签约金额_累计],
			 isnull(SUM(ISNULL(ActualMainRoomCAmount, 0)), 0)    AS [主房间签约金额_累计],
			 isnull(SUM(ISNULL(ActualAttachRoomCAmount, 0)), 0)  AS [附属房间签约金额_累计],
			 isnull(SUM(ISNULL(ActualMainRoomCBldArea, 0)), 0)   AS [主房间签约面积_累计],
			 isnull(SUM(ISNULL(ActualAttachRoomCBldArea, 0)), 0) AS [附属房间签约面积_累计],
			 isnull(SUM(ISNULL(ActualMainRoomCTs, 0)), 0)        AS [主房间签约套数_累计],
			 isnull(SUM(ISNULL(ActualAttachRoomCTs, 0)), 0)      AS [附属房间签约套数_累计],
			 ProjGUID,
			 ProjName,
			 ParentProjName,
			 ParentProjGUID,
			 BUGUID,
			 BUName
		 from (
				  SELECT case when isAttachRoom = 0 then RmbAmount else 0 end AS ActualCAmount,
						 case when isAttachRoom = 0 then RmbAmount - FsTotal else 0 end AS ActualMainRoomCAmount,
						 case when isAttachRoom = 1 then CjRoomTotal else 0 end AS ActualAttachRoomCAmount,
						 case when isAttachRoom = 0 then BldArea else 0 end as ActualMainRoomCBldArea,
						 case when isAttachRoom = 1 then BldArea else 0 end as ActualAttachRoomCBldArea,
						 case when isAttachRoom = 0 then ts else 0 end as ActualMainRoomCTs,
						 case when isAttachRoom = 1 then ts else 0 end as ActualAttachRoomCTs,
						 ts,
						 HsTjDate,
						 ProjGUID,
						 ProjName,
						 ParentProjName,
						 ParentProjGUID,
						 TopProductTypeName,
						 BUGUID,
						 BUName
				  FROM dbo.data_wide_s_SaleHsData WITH (NOLOCK)
				  WHERE TradeType = '签约'
			  ) A
		 group by BUGUID,
				  ProjGUID,
				  ProjName,
				  ParentProjName,
				  ParentProjGUID,
				  BUName
	 ),
	 -- 累计实际认购
	 [ActualOrder] as (
		 SELECT
			 /* 昨日认购 */
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='车库/库房'  then  ts else 0 end, 0)), 0)   AS [认购套数_车位昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [认购套数_住宅昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [认购套数_商业昨日],

			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='车库/库房'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_车位昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='住宅'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_住宅昨日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @yesterday) and TopProductTypeName='商业'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_商业昨日],

			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualOAmount else 0 end , 0)), 0)            AS [认购金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualMainRoomOAmount else 0 end , 0)), 0)    AS [主房间认购金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualAttachRoomOAmount else 0 end , 0)), 0)  AS [附属房间认购金额_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualMainRoomOBldArea else 0 end , 0)), 0)   AS [主房间认购面积_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualAttachRoomOBldArea else 0 end , 0)), 0) AS [附属房间认购面积_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualMainRoomOTs else 0 end , 0)), 0)        AS [主房间认购套数_昨日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @yesterday then ActualAttachRoomOTs else 0 end , 0)), 0)      AS [附属房间认购套数_昨日],
			 /* 本日认购 */
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @now) and TopProductTypeName='车库/库房'  then  ts else 0 end, 0)), 0)   AS [认购套数_车位本日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @now) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [认购套数_住宅本日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @now) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [认购套数_商业本日],

			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @now) and TopProductTypeName='车库/库房'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_车位本日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @now) and TopProductTypeName='住宅'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_住宅本日],
			 isnull(SUM(ISNULL(case when ( Cast(HsTjDate as Date) = @now) and TopProductTypeName='商业'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_商业本日],

			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualOAmount else 0 end , 0)), 0)            AS [认购金额_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualMainRoomOAmount else 0 end , 0)), 0)    AS [主房间认购金额_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualAttachRoomOAmount else 0 end , 0)), 0)  AS [附属房间认购金额_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualMainRoomOBldArea else 0 end , 0)), 0)   AS [主房间认购面积_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualAttachRoomOBldArea else 0 end , 0)), 0) AS [附属房间认购面积_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualMainRoomOTs else 0 end , 0)), 0)        AS [主房间认购套数_本日],
			 isnull(SUM(ISNULL(case when  Cast(HsTjDate as Date) = @now then ActualAttachRoomOTs else 0 end , 0)), 0)      AS [附属房间认购套数_本日],
			 /* 本周认购 */
			 isnull(SUM(ISNULL(case when ( HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='车库/库房'  then  ts else 0 end, 0)), 0)   AS [认购套数_车位本周],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [认购套数_住宅本周],
			 isnull(SUM(ISNULL(case when (  HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [认购套数_商业本周],

			 isnull(SUM(ISNULL(case when ( HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='车库/库房'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_车位本周],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='住宅'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_住宅本周],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @weekstartday and @weekendday) and TopProductTypeName='商业'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_商业本周],

			 isnull(SUM(ISNULL(case when  HsTjDate between @weekstartday and @weekendday then ActualOAmount else 0 end , 0)), 0)            AS [认购金额_本周],
			 isnull(SUM(ISNULL(case when  HsTjDate between @weekstartday and @weekendday then ActualMainRoomOAmount else 0 end , 0)), 0)    AS [主房间认购金额_本周],
			 isnull(SUM(ISNULL(case when  HsTjDate between @weekstartday and @weekendday then ActualAttachRoomOAmount else 0 end , 0)), 0)  AS [附属房间认购金额_本周],
			 isnull(SUM(ISNULL(case when  HsTjDate between @weekstartday and @weekendday then ActualMainRoomOBldArea else 0 end , 0)), 0)   AS [主房间认购面积_本周],
			 isnull(SUM(ISNULL(case when  HsTjDate between @weekstartday and @weekendday then ActualAttachRoomOBldArea else 0 end , 0)), 0) AS [附属房间认购面积_本周],
			 isnull(SUM(ISNULL(case when  HsTjDate between @weekstartday and @weekendday then ActualMainRoomOTs else 0 end , 0)), 0)        AS [主房间认购套数_本周],
			 isnull(SUM(ISNULL(case when  HsTjDate between @weekstartday and @weekendday then ActualAttachRoomOTs else 0 end , 0)), 0)      AS [附属房间认购套数_本周],
			 /* 本月认购 */
			 isnull(SUM(ISNULL(case when ( HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='车库/库房'  then  ts else 0 end, 0)), 0)   AS [认购套数_车位本月],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [认购套数_住宅本月],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [认购套数_商业本月],

			 isnull(SUM(ISNULL(case when ( HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='车库/库房'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_车位本月],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='住宅'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_住宅本月],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @monthstartday and @monthendday) and TopProductTypeName='商业'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_商业本月],


			 isnull(SUM(ISNULL(case when  HsTjDate between @monthstartday and @monthendday then ActualOAmount else 0 end , 0)), 0)            AS [认购金额_本月],
			 isnull(SUM(ISNULL(case when  HsTjDate between @monthstartday and @monthendday then ActualMainRoomOAmount else 0 end , 0)), 0)    AS [主房间认购金额_本月],
			 isnull(SUM(ISNULL(case when  HsTjDate between @monthstartday and @monthendday then ActualAttachRoomOAmount else 0 end , 0)), 0)  AS [附属房间认购金额_本月],
			 isnull(SUM(ISNULL(case when  HsTjDate between @monthstartday and @monthendday then ActualMainRoomOBldArea else 0 end , 0)), 0)   AS [主房间认购面积_本月],
			 isnull(SUM(ISNULL(case when  HsTjDate between @monthstartday and @monthendday then ActualAttachRoomOBldArea else 0 end , 0)), 0) AS [附属房间认购面积_本月],
			 isnull(SUM(ISNULL(case when  HsTjDate between @monthstartday and @monthendday then ActualMainRoomOTs else 0 end , 0)), 0)        AS [主房间认购套数_本月],
			 isnull(SUM(ISNULL(case when  HsTjDate between @monthstartday and @monthendday then ActualAttachRoomOTs else 0 end , 0)), 0)      AS [附属房间认购套数_本月],
			 /* 本季认购 */
			 isnull(SUM(ISNULL(case when ( HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='车库/库房'  then  ts else 0 end, 0)), 0)   AS [认购套数_车位本季],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [认购套数_住宅本季],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [认购套数_商业本季],

			 isnull(SUM(ISNULL(case when ( HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='车库/库房'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_车位本季],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='住宅'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_住宅本季],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @quarterstartday and @quarterendday) and TopProductTypeName='商业'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_商业本季],

			 isnull(SUM(ISNULL(case when  HsTjDate between @quarterstartday and @quarterendday then ActualOAmount else 0 end , 0)), 0)            AS [认购金额_本季],
			 isnull(SUM(ISNULL(case when  HsTjDate between @quarterstartday and @quarterendday then ActualMainRoomOAmount else 0 end , 0)), 0)    AS [主房间认购金额_本季],
			 isnull(SUM(ISNULL(case when  HsTjDate between @quarterstartday and @quarterendday then ActualAttachRoomOAmount else 0 end , 0)), 0)  AS [附属房间认购金额_本季],
			 isnull(SUM(ISNULL(case when  HsTjDate between @quarterstartday and @quarterendday then ActualMainRoomOBldArea else 0 end , 0)), 0)   AS [主房间认购面积_本季],
			 isnull(SUM(ISNULL(case when  HsTjDate between @quarterstartday and @quarterendday then ActualAttachRoomOBldArea else 0 end , 0)), 0) AS [附属房间认购面积_本季],
			 isnull(SUM(ISNULL(case when  HsTjDate between @quarterstartday and @quarterendday then ActualMainRoomOTs else 0 end , 0)), 0)        AS [主房间认购套数_本季],
			 isnull(SUM(ISNULL(case when  HsTjDate between @quarterstartday and @quarterendday then ActualAttachRoomOTs else 0 end , 0)), 0)      AS [附属房间认购套数_本季],
			 /* 本年认购 */
			 isnull(SUM(ISNULL(case when ( HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='车库/库房'  then  ts else 0 end, 0)), 0)   AS [认购套数_车位本年],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [认购套数_住宅本年],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [认购套数_商业本年],

			 isnull(SUM(ISNULL(case when ( HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='车库/库房'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_车位本年],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='住宅'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_住宅本年],
			 isnull(SUM(ISNULL(case when ( HsTjDate between @yearstartday and @yearendday) and TopProductTypeName='商业'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_商业本年],

			 isnull(SUM(ISNULL(case when  HsTjDate between @yearstartday and @yearendday then ActualOAmount else 0 end , 0)), 0)            AS [认购金额_本年],
			 isnull(SUM(ISNULL(case when  HsTjDate between @yearstartday and @yearendday then ActualMainRoomOAmount else 0 end , 0)), 0)    AS [主房间认购金额_本年],
			 isnull(SUM(ISNULL(case when  HsTjDate between @yearstartday and @yearendday then ActualAttachRoomOAmount else 0 end , 0)), 0)  AS [附属房间认购金额_本年],
			 isnull(SUM(ISNULL(case when  HsTjDate between @yearstartday and @yearendday then ActualMainRoomOBldArea else 0 end , 0)), 0)   AS [主房间认购面积_本年],
			 isnull(SUM(ISNULL(case when  HsTjDate between @yearstartday and @yearendday then ActualAttachRoomOBldArea else 0 end , 0)), 0) AS [附属房间认购面积_本年],
			 isnull(SUM(ISNULL(case when  HsTjDate between @yearstartday and @yearendday then ActualMainRoomOTs else 0 end , 0)), 0)        AS [主房间认购套数_本年],
			 isnull(SUM(ISNULL(case when  HsTjDate between @yearstartday and @yearendday then ActualAttachRoomOTs else 0 end , 0)), 0)      AS [附属房间认购套数_本年],
			 /* 累计认购 */
			 isnull(SUM(ISNULL(case when TopProductTypeName='车库/库房'  then  ts else 0 end, 0)), 0)   AS [认购套数_车位累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='住宅'  then  ts else 0 end, 0)), 0)   AS [认购套数_住宅累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='商业'  then  ts else 0 end, 0)), 0)   AS [认购套数_商业累计],

			 isnull(SUM(ISNULL(case when TopProductTypeName='车库/库房'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_车位累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='住宅'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_住宅累计],
			 isnull(SUM(ISNULL(case when TopProductTypeName='商业'  then  ActualOAmount else 0 end, 0)), 0)   AS [认购金额_商业累计],

			 isnull(SUM(ISNULL(ActualOAmount , 0)), 0)            AS [认购金额_累计],
			 isnull(SUM(ISNULL(ActualMainRoomOAmount , 0)), 0)    AS [主房间认购金额_累计],
			 isnull(SUM(ISNULL(ActualAttachRoomOAmount , 0)), 0)  AS [附属房间认购金额_累计],
			 isnull(SUM(ISNULL(ActualMainRoomOBldArea , 0)), 0)   AS [主房间认购面积_累计],
			 isnull(SUM(ISNULL(ActualAttachRoomOBldArea , 0)), 0) AS [附属房间认购面积_累计],
			 isnull(SUM(ISNULL(ActualMainRoomOTs , 0)), 0)        AS [主房间认购套数_累计],
			 isnull(SUM(ISNULL(ActualAttachRoomOTs , 0)), 0)      AS [附属房间认购套数_累计],
			 ProjGUID,
			 ProjName,
			 ParentProjName,
			 ParentProjGUID,
			 BUGUID,
			 BUName
		 from (
				  SELECT case when isAttachRoom = 0 then OCjTotal else 0 end AS ActualOAmount,
						 case when isAttachRoom = 0 then OCjTotal - OFsTotal else 0 end AS ActualMainRoomOAmount,
						 case when isAttachRoom = 1 then CjRoomTotal else 0 end AS ActualAttachRoomOAmount,
						 case when isAttachRoom = 0 then OCjBldArea else 0 end as ActualMainRoomOBldArea,
						 case when isAttachRoom = 1 then OCjBldArea else 0 end as ActualAttachRoomOBldArea,
						 case when isAttachRoom = 0 then Ts else 0 end as ActualMainRoomOTs,
						 case when isAttachRoom = 1 then Ts else 0 end as ActualAttachRoomOTs,ts,
						 HsTjDate,
						 ProjGUID,
						 ProjName,
						 ParentProjName,
						 ParentProjGUID,
						 TopProductTypeName,
						 BUGUID,
						 BUName
				  FROM dbo.data_wide_s_SaleHsData WITH (NOLOCK)
				  WHERE TradeType IN ('签约', '认购','小订')  and CreateReason<>'撤销签约' and CloseReason<>'撤销签约'
			  ) A
		 GROUP BY
			 ProjGUID,
			 ProjName,
			 ParentProjName,
			 ParentProjGUID,
			 BUGUID,
			 BUName
	 ),
	 [detailResult] as (
		 -- 公司
		 SELECT
			 /* 昨日回款 */
			 ISNULL([回款金额_车位昨日], 0)     AS [回款金额_车位昨日],
			 ISNULL([回款金额_住宅昨日], 0)     AS [回款金额_住宅昨日],
			 ISNULL([回款金额_商业昨日], 0)     AS [回款金额_商业昨日],

			 ISNULL([贷款类回款金额_昨日], 0)  AS [贷款类回款金额_昨日],
			 ISNULL([非贷款类回款金额_昨日], 0) AS [非贷款类回款金额_昨日],
			 ISNULL([补充协议款_昨日], 0)    AS [补充协议款_昨日],
			 ISNULL([回款金额_昨日], 0)     AS [回款金额_昨日],
			 ISNULL([楼款_模糊匹配_昨日], 0)    AS [楼款_模糊匹配_昨日],
			 ISNULL([首期_模糊匹配_昨日], 0)    AS [首期_模糊匹配_昨日],
			 ISNULL([定金_模糊匹配_昨日], 0)    AS [定金_模糊匹配_昨日],
			 ISNULL([其他_模糊匹配_昨日], 0)    AS [其他_模糊匹配_昨日],
			 /* 本日回款 */
			 ISNULL([回款金额_车位本日], 0)     AS [回款金额_车位本日],
			 ISNULL([回款金额_住宅本日], 0)     AS [回款金额_住宅本日],
			 ISNULL([回款金额_商业本日], 0)     AS [回款金额_商业本日],

			 ISNULL([贷款类回款金额_本日], 0)  AS [贷款类回款金额_本日],
			 ISNULL([非贷款类回款金额_本日], 0) AS [非贷款类回款金额_本日],
			 ISNULL([补充协议款_本日], 0)    AS [补充协议款_本日],
			 ISNULL([回款金额_本日], 0)     AS [回款金额_本日],
			 ISNULL([楼款_模糊匹配_本日], 0)    AS [楼款_模糊匹配_本日],
			 ISNULL([首期_模糊匹配_本日], 0)    AS [首期_模糊匹配_本日],
			 ISNULL([定金_模糊匹配_本日], 0)    AS [定金_模糊匹配_本日],
			 ISNULL([其他_模糊匹配_本日], 0)    AS [其他_模糊匹配_本日],
			 /* 本周回款 */
			 ISNULL([回款金额_车位本周], 0)     AS [回款金额_车位本周],
			 ISNULL([回款金额_住宅本周], 0)     AS [回款金额_住宅本周],
			 ISNULL([回款金额_商业本周], 0)     AS [回款金额_商业本周],

			 ISNULL([贷款类回款金额_本周], 0)  AS [贷款类回款金额_本周],
			 ISNULL([非贷款类回款金额_本周], 0) AS [非贷款类回款金额_本周],
			 ISNULL([补充协议款_本周], 0)    AS [补充协议款_本周],
			 ISNULL([回款金额_本周], 0)     AS [回款金额_本周],
			 ISNULL([楼款_模糊匹配_本周], 0)    AS [楼款_模糊匹配_本周],
			 ISNULL([首期_模糊匹配_本周], 0)    AS [首期_模糊匹配_本周],
			 ISNULL([定金_模糊匹配_本周], 0)    AS [定金_模糊匹配_本周],
			 ISNULL([其他_模糊匹配_本周], 0)    AS [其他_模糊匹配_本周],
			 /* 本月回款 */
			 ISNULL([回款金额_车位本月], 0)     AS [回款金额_车位本月],
			 ISNULL([回款金额_住宅本月], 0)     AS [回款金额_住宅本月],
			 ISNULL([回款金额_商业本月], 0)     AS [回款金额_商业本月],

			 ISNULL([贷款类回款金额_本月], 0)  AS [贷款类回款金额_本月],
			 ISNULL([非贷款类回款金额_本月], 0) AS [非贷款类回款金额_本月],
			 ISNULL([补充协议款_本月], 0)    AS [补充协议款_本月],
			 ISNULL([回款金额_本月], 0)     AS [回款金额_本月],
			 ISNULL([楼款_模糊匹配_本月], 0)    AS [楼款_模糊匹配_本月],
			 ISNULL([首期_模糊匹配_本月], 0)    AS [首期_模糊匹配_本月],
			 ISNULL([定金_模糊匹配_本月], 0)    AS [定金_模糊匹配_本月],
			 ISNULL([其他_模糊匹配_本月], 0)    AS [其他_模糊匹配_本月],
			 /* 本季回款 */
			 ISNULL([回款金额_车位本季], 0)     AS [回款金额_车位本季],
			 ISNULL([回款金额_住宅本季], 0)     AS [回款金额_住宅本季],
			 ISNULL([回款金额_商业本季], 0)     AS [回款金额_商业本季],

			 ISNULL([贷款类回款金额_本季], 0)  AS [贷款类回款金额_本季],
			 ISNULL([非贷款类回款金额_本季], 0) AS [非贷款类回款金额_本季],
			 ISNULL([补充协议款_本季], 0)    AS [补充协议款_本季],
			 ISNULL([回款金额_本季], 0)     AS [回款金额_本季],
			 ISNULL([楼款_模糊匹配_本季], 0)    AS [楼款_模糊匹配_本季],
			 ISNULL([首期_模糊匹配_本季], 0)    AS [首期_模糊匹配_本季],
			 ISNULL([定金_模糊匹配_本季], 0)    AS [定金_模糊匹配_本季],
			 ISNULL([其他_模糊匹配_本季], 0)    AS [其他_模糊匹配_本季],
			 /* 本年回款 */
			 ISNULL([回款金额_车位本年], 0)     AS [回款金额_车位本年],
			 ISNULL([回款金额_住宅本年], 0)     AS [回款金额_住宅本年],
			 ISNULL([回款金额_商业本年], 0)     AS [回款金额_商业本年],

			 ISNULL([贷款类回款金额_本年], 0)  AS [贷款类回款金额_本年],
			 ISNULL([非贷款类回款金额_本年], 0) AS [非贷款类回款金额_本年],
			 ISNULL([补充协议款_本年], 0)    AS [补充协议款_本年],
			 ISNULL([回款金额_本年], 0)     AS [回款金额_本年],
			 ISNULL([楼款_模糊匹配_本年], 0)    AS [楼款_模糊匹配_本年],
			 ISNULL([首期_模糊匹配_本年], 0)    AS [首期_模糊匹配_本年],
			 ISNULL([定金_模糊匹配_本年], 0)    AS [定金_模糊匹配_本年],
			 ISNULL([其他_模糊匹配_本年], 0)    AS [其他_模糊匹配_本年],
			 /* 累计回款 */
			 ISNULL([回款金额_车位累计], 0)     AS [回款金额_车位累计],
			 ISNULL([回款金额_住宅累计], 0)     AS [回款金额_住宅累计],
			 ISNULL([回款金额_商业累计], 0)     AS [回款金额_商业累计],

			 ISNULL([贷款类回款金额_累计], 0)  AS [贷款类回款金额_累计],
			 ISNULL([非贷款类回款金额_累计], 0) AS [非贷款类回款金额_累计],
			 ISNULL([补充协议款_累计], 0)    AS [补充协议款_累计],
			 ISNULL([回款金额_累计], 0)     AS [回款金额_累计],
			 ISNULL([楼款_模糊匹配_累计], 0)    AS [楼款_模糊匹配_累计],
			 ISNULL([首期_模糊匹配_累计], 0)    AS [首期_模糊匹配_累计],
			 ISNULL([定金_模糊匹配_累计], 0)    AS [定金_模糊匹配_累计],
			 ISNULL([其他_模糊匹配_累计], 0)    AS [其他_模糊匹配_累计],

			 /* 昨日认购 */
			 ISNULL([认购套数_车位昨日], 0)                   AS [认购套数_车位昨日],
			 ISNULL([认购套数_住宅昨日], 0)                   AS [认购套数_住宅昨日],
			 ISNULL([认购套数_商业昨日], 0)                   AS [认购套数_商业昨日],
			 ISNULL([认购金额_车位昨日], 0)                   AS [认购金额_车位昨日],
			 ISNULL([认购金额_住宅昨日], 0)                   AS [认购金额_住宅昨日],
			 ISNULL([认购金额_商业昨日], 0)                   AS [认购金额_商业昨日],

			 ISNULL([认购金额_昨日], 0)                   AS [认购金额_昨日],
			 ISNULL([主房间认购金额_昨日], 0)                AS [主房间认购金额_昨日],
			 ISNULL([附属房间认购金额_昨日], 0)               AS [附属房间认购金额_昨日],
			 ISNULL([主房间认购面积_昨日], 0)                AS [主房间认购面积_昨日],
			 ISNULL([附属房间认购面积_昨日], 0)               AS [附属房间认购面积_昨日],
			 ISNULL([主房间认购套数_昨日], 0)                AS [主房间认购套数_昨日],
			 ISNULL([附属房间认购套数_昨日], 0)               AS [附属房间认购套数_昨日],
			 /* 本日认购 */
			 ISNULL([认购套数_车位本日], 0)                   AS [认购套数_车位本日],
			 ISNULL([认购套数_住宅本日], 0)                   AS [认购套数_住宅本日],
			 ISNULL([认购套数_商业本日], 0)                   AS [认购套数_商业本日],
			 ISNULL([认购金额_车位本日], 0)                   AS [认购金额_车位本日],
			 ISNULL([认购金额_住宅本日], 0)                   AS [认购金额_住宅本日],
			 ISNULL([认购金额_商业本日], 0)                   AS [认购金额_商业本日],

			 ISNULL([认购金额_本日], 0)                   AS [认购金额_本日],
			 ISNULL([主房间认购金额_本日], 0)                AS [主房间认购金额_本日],
			 ISNULL([附属房间认购金额_本日], 0)               AS [附属房间认购金额_本日],
			 ISNULL([主房间认购面积_本日], 0)                AS [主房间认购面积_本日],
			 ISNULL([附属房间认购面积_本日], 0)               AS [附属房间认购面积_本日],
			 ISNULL([主房间认购套数_本日], 0)                AS [主房间认购套数_本日],
			 ISNULL([附属房间认购套数_本日], 0)               AS [附属房间认购套数_本日],
			 /* 本周认购 */
			 ISNULL([认购套数_车位本周], 0)                   AS [认购套数_车位本周],
			 ISNULL([认购套数_住宅本周], 0)                   AS [认购套数_住宅本周],
			 ISNULL([认购套数_商业本周], 0)                   AS [认购套数_商业本周],
			 ISNULL([认购金额_车位本周], 0)                   AS [认购金额_车位本周],
			 ISNULL([认购金额_住宅本周], 0)                   AS [认购金额_住宅本周],
			 ISNULL([认购金额_商业本周], 0)                   AS [认购金额_商业本周],

			 ISNULL([认购金额_本周], 0)                   AS [认购金额_本周],
			 ISNULL([主房间认购金额_本周], 0)                AS [主房间认购金额_本周],
			 ISNULL([附属房间认购金额_本周], 0)               AS [附属房间认购金额_本周],
			 ISNULL([主房间认购面积_本周], 0)                AS [主房间认购面积_本周],
			 ISNULL([附属房间认购面积_本周], 0)               AS [附属房间认购面积_本周],
			 ISNULL([主房间认购套数_本周], 0)                AS [主房间认购套数_本周],
			 ISNULL([附属房间认购套数_本周], 0)               AS [附属房间认购套数_本周],
			 /* 本月认购 */
			 ISNULL([认购套数_车位本月], 0)                   AS [认购套数_车位本月],
			 ISNULL([认购套数_住宅本月], 0)                   AS [认购套数_住宅本月],
			 ISNULL([认购套数_商业本月], 0)                   AS [认购套数_商业本月],
			 ISNULL([认购金额_车位本月], 0)                   AS [认购金额_车位本月],
			 ISNULL([认购金额_住宅本月], 0)                   AS [认购金额_住宅本月],
			 ISNULL([认购金额_商业本月], 0)                   AS [认购金额_商业本月],

			 ISNULL([认购金额_本月], 0)                   AS [认购金额_本月],
			 ISNULL([主房间认购金额_本月], 0)                AS [主房间认购金额_本月],
			 ISNULL([附属房间认购金额_本月], 0)               AS [附属房间认购金额_本月],
			 ISNULL([主房间认购面积_本月], 0)                AS [主房间认购面积_本月],
			 ISNULL([附属房间认购面积_本月], 0)               AS [附属房间认购面积_本月],
			 ISNULL([主房间认购套数_本月], 0)                AS [主房间认购套数_本月],
			 ISNULL([附属房间认购套数_本月], 0)               AS [附属房间认购套数_本月],
			 /* 本季认购 */
			 ISNULL([认购套数_车位本季], 0)                   AS [认购套数_车位本季],
			 ISNULL([认购套数_住宅本季], 0)                   AS [认购套数_住宅本季],
			 ISNULL([认购套数_商业本季], 0)                   AS [认购套数_商业本季],
			 ISNULL([认购金额_车位本季], 0)                   AS [认购金额_车位本季],
			 ISNULL([认购金额_住宅本季], 0)                   AS [认购金额_住宅本季],
			 ISNULL([认购金额_商业本季], 0)                   AS [认购金额_商业本季],

			 ISNULL([认购金额_本季], 0)                   AS [认购金额_本季],
			 ISNULL([主房间认购金额_本季], 0)                AS [主房间认购金额_本季],
			 ISNULL([附属房间认购金额_本季], 0)               AS [附属房间认购金额_本季],
			 ISNULL([主房间认购面积_本季], 0)                AS [主房间认购面积_本季],
			 ISNULL([附属房间认购面积_本季], 0)               AS [附属房间认购面积_本季],
			 ISNULL([主房间认购套数_本季], 0)                AS [主房间认购套数_本季],
			 ISNULL([附属房间认购套数_本季], 0)               AS [附属房间认购套数_本季],
			 /* 本年认购 */
			 ISNULL([认购套数_车位本年], 0)                   AS [认购套数_车位本年],
			 ISNULL([认购套数_住宅本年], 0)                   AS [认购套数_住宅本年],
			 ISNULL([认购套数_商业本年], 0)                   AS [认购套数_商业本年],
			 ISNULL([认购金额_车位本年], 0)                   AS [认购金额_车位本年],
			 ISNULL([认购金额_住宅本年], 0)                   AS [认购金额_住宅本年],
			 ISNULL([认购金额_商业本年], 0)                   AS [认购金额_商业本年],

			 ISNULL([认购金额_本年], 0)                   AS [认购金额_本年],
			 ISNULL([主房间认购金额_本年], 0)                AS [主房间认购金额_本年],
			 ISNULL([附属房间认购金额_本年], 0)               AS [附属房间认购金额_本年],
			 ISNULL([主房间认购面积_本年], 0)                AS [主房间认购面积_本年],
			 ISNULL([附属房间认购面积_本年], 0)               AS [附属房间认购面积_本年],
			 ISNULL([主房间认购套数_本年], 0)                AS [主房间认购套数_本年],
			 ISNULL([附属房间认购套数_本年], 0)               AS [附属房间认购套数_本年],
			 /* 累计认购 */
			 ISNULL([认购套数_车位累计], 0)                   AS [认购套数_车位累计],
			 ISNULL([认购套数_住宅累计], 0)                   AS [认购套数_住宅累计],
			 ISNULL([认购套数_商业累计], 0)                   AS [认购套数_商业累计],
			 ISNULL([认购金额_车位累计], 0)                   AS [认购金额_车位累计],
			 ISNULL([认购金额_住宅累计], 0)                   AS [认购金额_住宅累计],
			 ISNULL([认购金额_商业累计], 0)                   AS [认购金额_商业累计],

			 ISNULL([认购金额_累计], 0)                   AS [认购金额_累计],
			 ISNULL([主房间认购金额_累计], 0)                AS [主房间认购金额_累计],
			 ISNULL([附属房间认购金额_累计], 0)               AS [附属房间认购金额_累计],
			 ISNULL([主房间认购面积_累计], 0)                AS [主房间认购面积_累计],
			 ISNULL([附属房间认购面积_累计], 0)               AS [附属房间认购面积_累计],
			 ISNULL([主房间认购套数_累计], 0)                AS [主房间认购套数_累计],
			 ISNULL([附属房间认购套数_累计], 0)               AS [附属房间认购套数_累计],

			  /*三科需求*/
			  ISNULL([签约套数_赠送车位昨日], 0)   AS [签约套数_赠送车位昨日] ,
			 ISNULL([签约套数_赠送车位本日], 0)   AS [签约套数_赠送车位本日],
			  ISNULL([签约套数_赠送车位本周], 0)   AS [签约套数_赠送车位本周],
			 ISNULL([签约套数_赠送车位本月], 0)   AS [签约套数_赠送车位本月],
			  ISNULL([签约套数_赠送车位本季], 0)   AS [签约套数_赠送车位本季],
			 ISNULL([签约套数_赠送车位本年], 0)   AS [签约套数_赠送车位本年],
			 ISNULL([签约套数_赠送车位累计], 0)   AS [签约套数_赠送车位累计],


			 /* 昨日签约 */
			 ISNULL([签约套数_车位昨日], 0)                   AS [签约套数_车位昨日],
			 ISNULL([签约套数_住宅昨日], 0)                   AS [签约套数_住宅昨日],
			 ISNULL([签约套数_商业昨日], 0)                   AS [签约套数_商业昨日],
			 ISNULL([签约金额_车位昨日], 0)                   AS [签约金额_车位昨日],
			 ISNULL([签约金额_住宅昨日], 0)                   AS [签约金额_住宅昨日],
			 ISNULL([签约金额_商业昨日], 0)                   AS [签约金额_商业昨日],

			 ISNULL([签约金额_昨日], 0)                   AS [签约金额_昨日],
			 ISNULL([主房间签约金额_昨日], 0)                AS [主房间签约金额_昨日],
			 ISNULL([附属房间签约金额_昨日], 0)               AS [附属房间签约金额_昨日],
			 ISNULL([主房间签约面积_昨日], 0)                AS [主房间签约面积_昨日],
			 ISNULL([附属房间签约面积_昨日], 0)               AS [附属房间签约面积_昨日],
			 ISNULL([主房间签约套数_昨日], 0)                AS [主房间签约套数_昨日],
			 ISNULL([附属房间签约套数_昨日], 0)               AS [附属房间签约套数_昨日],
			 /* 本日签约 */
			 ISNULL([签约套数_车位本日], 0)                   AS [签约套数_车位本日],
			 ISNULL([签约套数_住宅本日], 0)                   AS [签约套数_住宅本日],
			 ISNULL([签约套数_商业本日], 0)                   AS [签约套数_商业本日],
			 ISNULL([签约金额_车位本日], 0)                   AS [签约金额_车位本日],
			 ISNULL([签约金额_住宅本日], 0)                   AS [签约金额_住宅本日],
			 ISNULL([签约金额_商业本日], 0)                   AS [签约金额_商业本日],

			 ISNULL([签约金额_本日], 0)                   AS [签约金额_本日],
			 ISNULL([主房间签约金额_本日], 0)                AS [主房间签约金额_本日],
			 ISNULL([附属房间签约金额_本日], 0)               AS [附属房间签约金额_本日],
			 ISNULL([主房间签约面积_本日], 0)                AS [主房间签约面积_本日],
			 ISNULL([附属房间签约面积_本日], 0)               AS [附属房间签约面积_本日],
			 ISNULL([主房间签约套数_本日], 0)                AS [主房间签约套数_本日],
			 ISNULL([附属房间签约套数_本日], 0)               AS [附属房间签约套数_本日],
			 /* 本周签约 */
			 ISNULL([签约套数_车位本周], 0)                   AS [签约套数_车位本周],
			 ISNULL([签约套数_住宅本周], 0)                   AS [签约套数_住宅本周],
			 ISNULL([签约套数_商业本周], 0)                   AS [签约套数_商业本周],
			 ISNULL([签约金额_车位本周], 0)                   AS [签约金额_车位本周],
			 ISNULL([签约金额_住宅本周], 0)                   AS [签约金额_住宅本周],
			 ISNULL([签约金额_商业本周], 0)                   AS [签约金额_商业本周],

			 ISNULL([签约金额_本周], 0)                   AS [签约金额_本周],
			 ISNULL([主房间签约金额_本周], 0)                AS [主房间签约金额_本周],
			 ISNULL([附属房间签约金额_本周], 0)               AS [附属房间签约金额_本周],
			 ISNULL([主房间签约面积_本周], 0)                AS [主房间签约面积_本周],
			 ISNULL([附属房间签约面积_本周], 0)               AS [附属房间签约面积_本周],
			 ISNULL([主房间签约套数_本周], 0)                AS [主房间签约套数_本周],
			 ISNULL([附属房间签约套数_本周], 0)               AS [附属房间签约套数_本周],
			 /* 本月签约 */
			 ISNULL([签约套数_车位本月], 0)                   AS [签约套数_车位本月],
			 ISNULL([签约套数_住宅本月], 0)                   AS [签约套数_住宅本月],
			 ISNULL([签约套数_商业本月], 0)                   AS [签约套数_商业本月],
			 ISNULL([签约金额_车位本月], 0)                   AS [签约金额_车位本月],
			 ISNULL([签约金额_住宅本月], 0)                   AS [签约金额_住宅本月],
			 ISNULL([签约金额_商业本月], 0)                   AS [签约金额_商业本月],

			 ISNULL([签约金额_本月], 0)                   AS [签约金额_本月],
			 ISNULL([主房间签约金额_本月], 0)                AS [主房间签约金额_本月],
			 ISNULL([附属房间签约金额_本月], 0)               AS [附属房间签约金额_本月],
			 ISNULL([主房间签约面积_本月], 0)                AS [主房间签约面积_本月],
			 ISNULL([附属房间签约面积_本月], 0)               AS [附属房间签约面积_本月],
			 ISNULL([主房间签约套数_本月], 0)                AS [主房间签约套数_本月],
			 ISNULL([附属房间签约套数_本月], 0)               AS [附属房间签约套数_本月],
			 /* 本季签约 */
			 ISNULL([签约套数_车位本季], 0)                   AS [签约套数_车位本季],
			 ISNULL([签约套数_住宅本季], 0)                   AS [签约套数_住宅本季],
			 ISNULL([签约套数_商业本季], 0)                   AS [签约套数_商业本季],
			 ISNULL([签约金额_车位本季], 0)                   AS [签约金额_车位本季],
			 ISNULL([签约金额_住宅本季], 0)                   AS [签约金额_住宅本季],
			 ISNULL([签约金额_商业本季], 0)                   AS [签约金额_商业本季],

			 ISNULL([签约金额_本季], 0)                   AS [签约金额_本季],
			 ISNULL([主房间签约金额_本季], 0)                AS [主房间签约金额_本季],
			 ISNULL([附属房间签约金额_本季], 0)               AS [附属房间签约金额_本季],
			 ISNULL([主房间签约面积_本季], 0)                AS [主房间签约面积_本季],
			 ISNULL([附属房间签约面积_本季], 0)               AS [附属房间签约面积_本季],
			 ISNULL([主房间签约套数_本季], 0)                AS [主房间签约套数_本季],
			 ISNULL([附属房间签约套数_本季], 0)               AS [附属房间签约套数_本季],
			 /* 本年签约 */
			 ISNULL([签约套数_车位本年], 0)                   AS [签约套数_车位本年],
			 ISNULL([签约套数_住宅本年], 0)                   AS [签约套数_住宅本年],
			 ISNULL([签约套数_商业本年], 0)                   AS [签约套数_商业本年],
			 ISNULL([签约金额_车位本年], 0)                   AS [签约金额_车位本年],
			 ISNULL([签约金额_住宅本年], 0)                   AS [签约金额_住宅本年],
			 ISNULL([签约金额_商业本年], 0)                   AS [签约金额_商业本年],

			 ISNULL([签约金额_本年], 0)                   AS [签约金额_本年],
			 ISNULL([主房间签约金额_本年], 0)                AS [主房间签约金额_本年],
			 ISNULL([附属房间签约金额_本年], 0)               AS [附属房间签约金额_本年],
			 ISNULL([主房间签约面积_本年], 0)                AS [主房间签约面积_本年],
			 ISNULL([附属房间签约面积_本年], 0)               AS [附属房间签约面积_本年],
			 ISNULL([主房间签约套数_本年], 0)                AS [主房间签约套数_本年],
			 ISNULL([附属房间签约套数_本年], 0)               AS [附属房间签约套数_本年],
			 /* 累计签约 */
			 ISNULL([签约套数_车位累计], 0)                   AS [签约套数_车位累计],
			 ISNULL([签约套数_住宅累计], 0)                   AS [签约套数_住宅累计],
			 ISNULL([签约套数_商业累计], 0)                   AS [签约套数_商业累计],
			 ISNULL([签约金额_车位累计], 0)                   AS [签约金额_车位累计],
			 ISNULL([签约金额_住宅累计], 0)                   AS [签约金额_住宅累计],
			 ISNULL([签约金额_商业累计], 0)                   AS [签约金额_商业累计],

			 ISNULL([签约金额_累计], 0)                   AS [签约金额_累计],
			 ISNULL([主房间签约金额_累计], 0)                AS [主房间签约金额_累计],
			 ISNULL([附属房间签约金额_累计], 0)               AS [附属房间签约金额_累计],
			 ISNULL([主房间签约面积_累计], 0)                AS [主房间签约面积_累计],
			 ISNULL([附属房间签约面积_累计], 0)               AS [附属房间签约面积_累计],
			 ISNULL([主房间签约套数_累计], 0)                AS [主房间签约套数_累计],
			 ISNULL([附属房间签约套数_累计], 0)               AS [附属房间签约套数_累计],
			 isnull(proj.ParentGUID, proj.BUGUID)   as [父级GUID],
			 proj.ProjGuid                          as [GUID],
			 Proj.ProjName                          as [名称],
			 isnull(Proj.ParentProjName, bu.BUName) as [父级名称],
			 proj.BUGUID                            as [公司GUID],
			 bu.BUName                              as [公司名称],
			 proj.HierarchyCode                     as [排序号]
		 FROM proj
				  join bu on bu.BUGUID = proj.BUGUID
				  left join ActualGetIn on proj.projGuid = ActualGetIn.ProjGUID
				  left join ActualOrder on proj.projGuid = ActualOrder.ProjGUID
				  left join ActualContract on proj.projGuid = ActualContract.ProjGUID
	 )

select
	/*三科需求*/
	[签约套数_赠送车位昨日] ,
	[签约套数_赠送车位本日],
	[签约套数_赠送车位本周],
	[签约套数_赠送车位本月],
	[签约套数_赠送车位本季],
	[签约套数_赠送车位本年],
	[签约套数_赠送车位累计],
				
	Convert(decimal(18, 4),	[回款金额_车位昨日]/10000.00) AS [回款金额_车位昨日],
	Convert(decimal(18, 4),	[回款金额_住宅昨日]/10000.00) AS [回款金额_住宅昨日],
	Convert(decimal(18, 4),	[回款金额_商业昨日]/10000.00) AS [回款金额_商业昨日],
	Convert(decimal(18, 4),	[回款金额_车位本日]/10000.00) AS [回款金额_车位本日],
	Convert(decimal(18, 4),	[回款金额_住宅本日]/10000.00) AS [回款金额_住宅本日],
	Convert(decimal(18, 4),	[回款金额_商业本日]/10000.00) AS [回款金额_商业本日],
	Convert(decimal(18, 4),	[回款金额_车位本周]/10000.00) AS [回款金额_车位本周],
	Convert(decimal(18, 4),	[回款金额_住宅本周]/10000.00) AS [回款金额_住宅本周],
	Convert(decimal(18, 4),	[回款金额_商业本周]/10000.00) AS [回款金额_商业本周],
	Convert(decimal(18, 4),	[回款金额_车位本月]/10000.00) AS [回款金额_车位本月],
	Convert(decimal(18, 4),	[回款金额_住宅本月]/10000.00) AS [回款金额_住宅本月],
	Convert(decimal(18, 4),	[回款金额_商业本月]/10000.00) AS [回款金额_商业本月],
	Convert(decimal(18, 4),	[回款金额_车位本季]/10000.00) AS [回款金额_车位本季],
	Convert(decimal(18, 4),	[回款金额_住宅本季]/10000.00) AS [回款金额_住宅本季],
	Convert(decimal(18, 4),	[回款金额_商业本季]/10000.00) AS [回款金额_商业本季],
	Convert(decimal(18, 4),	[回款金额_车位本年]/10000.00) AS [回款金额_车位本年],
	Convert(decimal(18, 4),	[回款金额_住宅本年]/10000.00) AS [回款金额_住宅本年],
	Convert(decimal(18, 4),	[回款金额_商业本年]/10000.00) AS [回款金额_商业本年],
	Convert(decimal(18, 4),	[回款金额_车位累计]/10000.00) AS [回款金额_车位累计],
	Convert(decimal(18, 4),	[回款金额_住宅累计]/10000.00) AS [回款金额_住宅累计],
	Convert(decimal(18, 4),	[回款金额_商业累计]/10000.00) AS [回款金额_商业累计],

	[认购套数_车位昨日],
	[认购套数_住宅昨日],
	[认购套数_商业昨日],
	[认购套数_车位本日],
	[认购套数_住宅本日],
	[认购套数_商业本日],
	[认购套数_车位本周],
	[认购套数_住宅本周],
	[认购套数_商业本周],
	[认购套数_车位本月],
	[认购套数_住宅本月],
	[认购套数_商业本月],
	[认购套数_车位本季],
	[认购套数_住宅本季],
	[认购套数_商业本季],
	[认购套数_车位本年],
	[认购套数_住宅本年],
	[认购套数_商业本年],
	[认购套数_车位累计],
	[认购套数_住宅累计],
	[认购套数_商业累计],

	Convert(decimal(18, 4),	[认购金额_车位昨日]/ 10000.00) AS [认购金额_车位昨日],
	Convert(decimal(18, 4),	[认购金额_住宅昨日]/ 10000.00) AS [认购金额_住宅昨日],
	Convert(decimal(18, 4),	[认购金额_商业昨日]/ 10000.00) AS [认购金额_商业昨日],
	Convert(decimal(18, 4),	[认购金额_车位本日]/ 10000.00) AS [认购金额_车位本日],
	Convert(decimal(18, 4),	[认购金额_住宅本日]/ 10000.00) AS [认购金额_住宅本日],
	Convert(decimal(18, 4),	[认购金额_商业本日]/ 10000.00) AS [认购金额_商业本日],
	Convert(decimal(18, 4),	[认购金额_车位本周]/ 10000.00) AS [认购金额_车位本周],
	Convert(decimal(18, 4),	[认购金额_住宅本周]/ 10000.00) AS [认购金额_住宅本周],
	Convert(decimal(18, 4),	[认购金额_商业本周]/ 10000.00) AS [认购金额_商业本周],
	Convert(decimal(18, 4),	[认购金额_车位本月]/ 10000.00) AS [认购金额_车位本月],
	Convert(decimal(18, 4),	[认购金额_住宅本月]/ 10000.00) AS [认购金额_住宅本月],
	Convert(decimal(18, 4),	[认购金额_商业本月]/ 10000.00) AS [认购金额_商业本月],
	Convert(decimal(18, 4),	[认购金额_车位本季]/ 10000.00) AS [认购金额_车位本季],
	Convert(decimal(18, 4),	[认购金额_住宅本季]/ 10000.00) AS [认购金额_住宅本季],
	Convert(decimal(18, 4),	[认购金额_商业本季]/ 10000.00) AS [认购金额_商业本季],
	Convert(decimal(18, 4),	[认购金额_车位本年]/ 10000.00) AS [认购金额_车位本年],
	Convert(decimal(18, 4),	[认购金额_住宅本年]/ 10000.00) AS [认购金额_住宅本年],
	Convert(decimal(18, 4),	[认购金额_商业本年]/ 10000.00) AS [认购金额_商业本年],
	Convert(decimal(18, 4),	[认购金额_车位累计]/ 10000.00) AS [认购金额_车位累计],
	Convert(decimal(18, 4),	[认购金额_住宅累计]/ 10000.00) AS [认购金额_住宅累计],
	Convert(decimal(18, 4),	[认购金额_商业累计]/ 10000.00) AS [认购金额_商业累计],

	[签约套数_车位昨日],
	[签约套数_住宅昨日],
	[签约套数_商业昨日],
	[签约套数_车位本日],
	[签约套数_住宅本日],
	[签约套数_商业本日],
	[签约套数_车位本周],
	[签约套数_住宅本周],
	[签约套数_商业本周],
	[签约套数_车位本月],
	[签约套数_住宅本月],
	[签约套数_商业本月],
	[签约套数_车位本季],
	[签约套数_住宅本季],
	[签约套数_商业本季],
	[签约套数_车位本年],
	[签约套数_住宅本年],
	[签约套数_商业本年],
	[签约套数_车位累计],
	[签约套数_住宅累计],
	[签约套数_商业累计],

	Convert(decimal(18, 4),	[签约金额_车位昨日]/ 10000.00) AS [签约金额_车位昨日],
	Convert(decimal(18, 4),	[签约金额_住宅昨日]/ 10000.00) AS [签约金额_住宅昨日],
	Convert(decimal(18, 4),	[签约金额_商业昨日]/ 10000.00) AS [签约金额_商业昨日],
	Convert(decimal(18, 4),	[签约金额_车位本日]/ 10000.00) AS [签约金额_车位本日],
	Convert(decimal(18, 4),	[签约金额_住宅本日]/ 10000.00) AS [签约金额_住宅本日],
	Convert(decimal(18, 4),	[签约金额_商业本日]/ 10000.00) AS [签约金额_商业本日],
	Convert(decimal(18, 4),	[签约金额_车位本周]/ 10000.00) AS [签约金额_车位本周],
	Convert(decimal(18, 4),	[签约金额_住宅本周]/ 10000.00) AS [签约金额_住宅本周],
	Convert(decimal(18, 4),	[签约金额_商业本周]/ 10000.00) AS [签约金额_商业本周],
	Convert(decimal(18, 4),	[签约金额_车位本月]/ 10000.00) AS [签约金额_车位本月],
	Convert(decimal(18, 4),	[签约金额_住宅本月]/ 10000.00) AS [签约金额_住宅本月],
	Convert(decimal(18, 4),	[签约金额_商业本月]/ 10000.00) AS [签约金额_商业本月],
	Convert(decimal(18, 4),	[签约金额_车位本季]/ 10000.00) AS [签约金额_车位本季],
	Convert(decimal(18, 4),	[签约金额_住宅本季]/ 10000.00) AS [签约金额_住宅本季],
	Convert(decimal(18, 4),	[签约金额_商业本季]/ 10000.00) AS [签约金额_商业本季],
	Convert(decimal(18, 4),	[签约金额_车位本年]/ 10000.00) AS [签约金额_车位本年],
	Convert(decimal(18, 4),	[签约金额_住宅本年]/ 10000.00) AS [签约金额_住宅本年],
	Convert(decimal(18, 4),	[签约金额_商业本年]/ 10000.00) AS [签约金额_商业本年],
	Convert(decimal(18, 4),	[签约金额_车位累计]/ 10000.00) AS [签约金额_车位累计],
	Convert(decimal(18, 4),	[签约金额_住宅累计]/ 10000.00) AS [签约金额_住宅累计],
	Convert(decimal(18, 4),	[签约金额_商业累计]/ 10000.00) AS [签约金额_商业累计],
	/* 昨日回款 */

	Convert(decimal(18, 4), [贷款类回款金额_昨日] / 10000.00)  as [贷款类回款金额_昨日],
	Convert(decimal(18, 4), [非贷款类回款金额_昨日] / 10000.00) as [非贷款类回款金额_昨日],
	Convert(decimal(18, 4), [补充协议款_昨日] / 10000.00)    as [补充协议款_昨日],
	Convert(decimal(18, 4), [回款金额_昨日] / 10000.00)     as [回款金额_昨日],
	Convert(decimal(18, 4), [楼款_模糊匹配_昨日]/ 10000.00)  as [楼款_模糊匹配_昨日],
	Convert(decimal(18, 4), [首期_模糊匹配_昨日]/ 10000.00)  as [首期_模糊匹配_昨日],
	Convert(decimal(18, 4), [定金_模糊匹配_昨日]/ 10000.00)  as [定金_模糊匹配_昨日],
	Convert(decimal(18, 4), [其他_模糊匹配_昨日]/ 10000.00)  as [其他_模糊匹配_昨日],
/* 本日回款 */
	Convert(decimal(18, 4), [贷款类回款金额_本日] / 10000.00)  as [贷款类回款金额_本日],
	Convert(decimal(18, 4), [非贷款类回款金额_本日] / 10000.00) as [非贷款类回款金额_本日],
	Convert(decimal(18, 4), [补充协议款_本日] / 10000.00)    as [补充协议款_本日],
	Convert(decimal(18, 4), [回款金额_本日] / 10000.00)     as [回款金额_本日],
	Convert(decimal(18, 4), [楼款_模糊匹配_本日]/ 10000.00)  as [楼款_模糊匹配_本日],
	Convert(decimal(18, 4), [首期_模糊匹配_本日]/ 10000.00)  as [首期_模糊匹配_本日],
	Convert(decimal(18, 4), [定金_模糊匹配_本日]/ 10000.00)  as [定金_模糊匹配_本日],
	Convert(decimal(18, 4), [其他_模糊匹配_本日]/ 10000.00)  as [其他_模糊匹配_本日],
/* 本周回款 */
	Convert(decimal(18, 4), [贷款类回款金额_本周] / 10000.00)  as [贷款类回款金额_本周],
	Convert(decimal(18, 4), [非贷款类回款金额_本周] / 10000.00) as [非贷款类回款金额_本周],
	Convert(decimal(18, 4), [补充协议款_本周] / 10000.00)    as [补充协议款_本周],
	Convert(decimal(18, 4), [回款金额_本周] / 10000.00)     as [回款金额_本周],
	Convert(decimal(18, 4), [楼款_模糊匹配_本周]/ 10000.00)  as [楼款_模糊匹配_本周],
	Convert(decimal(18, 4), [首期_模糊匹配_本周]/ 10000.00)  as [首期_模糊匹配_本周],
	Convert(decimal(18, 4), [定金_模糊匹配_本周]/ 10000.00)  as [定金_模糊匹配_本周],
	Convert(decimal(18, 4), [其他_模糊匹配_本周]/ 10000.00)  as [其他_模糊匹配_本周],
/* 本月回款 */
	Convert(decimal(18, 4), [贷款类回款金额_本月] / 10000.00)  as [贷款类回款金额_本月],
	Convert(decimal(18, 4), [非贷款类回款金额_本月] / 10000.00) as [非贷款类回款金额_本月],
	Convert(decimal(18, 4), [补充协议款_本月] / 10000.00)    as [补充协议款_本月],
	Convert(decimal(18, 4), [回款金额_本月] / 10000.00)     as [回款金额_本月],
	Convert(decimal(18, 4), [楼款_模糊匹配_本月]/ 10000.00)  as [楼款_模糊匹配_本月],
	Convert(decimal(18, 4), [首期_模糊匹配_本月]/ 10000.00)  as [首期_模糊匹配_本月],
	Convert(decimal(18, 4), [定金_模糊匹配_本月]/ 10000.00)  as [定金_模糊匹配_本月],
	Convert(decimal(18, 4), [其他_模糊匹配_本月]/ 10000.00)  as [其他_模糊匹配_本月],
/* 本季回款 */
	Convert(decimal(18, 4), [贷款类回款金额_本季] / 10000.00)  as [贷款类回款金额_本季],
	Convert(decimal(18, 4), [非贷款类回款金额_本季] / 10000.00) as [非贷款类回款金额_本季],
	Convert(decimal(18, 4), [补充协议款_本季] / 10000.00)    as [补充协议款_本季],
	Convert(decimal(18, 4), [回款金额_本季] / 10000.00)     as [回款金额_本季],
	Convert(decimal(18, 4), [楼款_模糊匹配_本季]/ 10000.00)  as [楼款_模糊匹配_本季],
	Convert(decimal(18, 4), [首期_模糊匹配_本季]/ 10000.00)  as [首期_模糊匹配_本季],
	Convert(decimal(18, 4), [定金_模糊匹配_本季]/ 10000.00)  as [定金_模糊匹配_本季],
	Convert(decimal(18, 4), [其他_模糊匹配_本季]/ 10000.00)  as [其他_模糊匹配_本季],
/* 本年回款 */
	Convert(decimal(18, 4), [贷款类回款金额_本年] / 10000.00)  as [贷款类回款金额_本年],
	Convert(decimal(18, 4), [非贷款类回款金额_本年] / 10000.00) as [非贷款类回款金额_本年],
	Convert(decimal(18, 4), [补充协议款_本年] / 10000.00)    as [补充协议款_本年],
	Convert(decimal(18, 4), [回款金额_本年] / 10000.00)     as [回款金额_本年],
	Convert(decimal(18, 4), [楼款_模糊匹配_本年]/ 10000.00)  as [楼款_模糊匹配_本年],
	Convert(decimal(18, 4), [首期_模糊匹配_本年]/ 10000.00)  as [首期_模糊匹配_本年],
	Convert(decimal(18, 4), [定金_模糊匹配_本年]/ 10000.00)  as [定金_模糊匹配_本年],
	Convert(decimal(18, 4), [其他_模糊匹配_本年]/ 10000.00)  as [其他_模糊匹配_本年],
/* 累计回款 */
	Convert(decimal(18, 4), [贷款类回款金额_累计] / 10000.00)  as [贷款类回款金额_累计],
	Convert(decimal(18, 4), [非贷款类回款金额_累计] / 10000.00) as [非贷款类回款金额_累计],
	Convert(decimal(18, 4), [补充协议款_累计] / 10000.00)    as [补充协议款_累计],
	Convert(decimal(18, 4), [回款金额_累计] / 10000.00)     as [回款金额_累计],
	Convert(decimal(18, 4), [楼款_模糊匹配_累计]/ 10000.00)  as [楼款_模糊匹配_累计],
	Convert(decimal(18, 4), [首期_模糊匹配_累计]/ 10000.00)  as [首期_模糊匹配_累计],
	Convert(decimal(18, 4), [定金_模糊匹配_累计]/ 10000.00)  as [定金_模糊匹配_累计],
	Convert(decimal(18, 4), [其他_模糊匹配_累计]/ 10000.00)  as [其他_模糊匹配_累计],

	/* 昨日认购 */
	Convert(decimal(18, 4),[认购金额_昨日]/10000.00) as [认购金额_昨日] ,
	Convert(decimal(18, 4),[主房间认购金额_昨日]/10000.00) as [主房间认购金额_昨日] ,
	Convert(decimal(18, 4),[附属房间认购金额_昨日]/10000.00) as [附属房间认购金额_昨日] ,
	Convert(decimal(18, 4),case when [主房间认购面积_昨日] =0 then [认购金额_昨日] else [认购金额_昨日]/[主房间认购面积_昨日] end) as [认购均价_昨日],
	[主房间认购面积_昨日],
	[附属房间认购面积_昨日],
	[主房间认购套数_昨日],
	[附属房间认购套数_昨日],
	/* 本日认购 */
	Convert(decimal(18, 4),[认购金额_本日]/10000.00) as [认购金额_本日] ,
	Convert(decimal(18, 4),[主房间认购金额_本日]/10000.00) as [主房间认购金额_本日] ,
	Convert(decimal(18, 4),[附属房间认购金额_本日]/10000.00) as [附属房间认购金额_本日] ,
	Convert(decimal(18, 4),case when [主房间认购面积_本日] =0 then [认购金额_本日] else [认购金额_本日]/[主房间认购面积_本日] end) as [认购均价_本日],
	[主房间认购面积_本日],
	[附属房间认购面积_本日],
	[主房间认购套数_本日],
	[附属房间认购套数_本日],
	/* 本周认购 */
	Convert(decimal(18, 4),[认购金额_本周]/10000.00) as [认购金额_本周] ,
	Convert(decimal(18, 4),[主房间认购金额_本周]/10000.00) as [主房间认购金额_本周] ,
	Convert(decimal(18, 4),[附属房间认购金额_本周]/10000.00) as [附属房间认购金额_本周] ,
	Convert(decimal(18, 4),case when [主房间认购面积_本周] =0 then [认购金额_本周] else [认购金额_本周]/[主房间认购面积_本周] end) as [认购均价_本周],
	[主房间认购面积_本周],
	[附属房间认购面积_本周],
	[主房间认购套数_本周],
	[附属房间认购套数_本周],
	/* 本月认购 */
	Convert(decimal(18, 4),[认购金额_本月]/10000.00) as [认购金额_本月] ,
	Convert(decimal(18, 4),[主房间认购金额_本月]/10000.00) as [主房间认购金额_本月] ,
	Convert(decimal(18, 4),[附属房间认购金额_本月]/10000.00) as [附属房间认购金额_本月] ,
	Convert(decimal(18, 4),case when [主房间认购面积_本月] =0 then [认购金额_本月] else [认购金额_本月]/[主房间认购面积_本月] end) as [认购均价_本月],
	[主房间认购面积_本月],
	[附属房间认购面积_本月],
	[主房间认购套数_本月],
	[附属房间认购套数_本月],
	/* 本季认购 */
	Convert(decimal(18, 4),[认购金额_本季]/10000.00) as [认购金额_本季] ,
	Convert(decimal(18, 4),[主房间认购金额_本季]/10000.00) as [主房间认购金额_本季] ,
	Convert(decimal(18, 4),[附属房间认购金额_本季]/10000.00) as [附属房间认购金额_本季] ,
	Convert(decimal(18, 4),case when [主房间认购面积_本季] =0 then [认购金额_本季] else [认购金额_本季]/[主房间认购面积_本季] end) as [认购均价_本季],
	[主房间认购面积_本季],
	[附属房间认购面积_本季],
	[主房间认购套数_本季],
	[附属房间认购套数_本季],
	/* 本年认购 */
	Convert(decimal(18, 4),[认购金额_本年]/10000.00) as [认购金额_本年] ,
	Convert(decimal(18, 4),[主房间认购金额_本年]/10000.00) as [主房间认购金额_本年] ,
	Convert(decimal(18, 4),[附属房间认购金额_本年]/10000.00) as [附属房间认购金额_本年] ,
	Convert(decimal(18, 4),case when [主房间认购面积_本年] =0 then [认购金额_本年] else [认购金额_本年]/[主房间认购面积_本年] end) as [认购均价_本年],
	[主房间认购面积_本年],
	[附属房间认购面积_本年],
	[主房间认购套数_本年],
	[附属房间认购套数_本年],
	/* 累计认购 */
	Convert(decimal(18, 4),[认购金额_累计]/10000.00) as [认购金额_累计] ,
	Convert(decimal(18, 4),[主房间认购金额_累计]/10000.00) as [主房间认购金额_累计] ,
	Convert(decimal(18, 4),[附属房间认购金额_累计]/10000.00) as [附属房间认购金额_累计] ,
	Convert(decimal(18, 4),case when [主房间认购面积_累计] =0 then [认购金额_累计] else [认购金额_累计]/[主房间认购面积_累计] end) as [认购均价_累计],
	[主房间认购面积_累计],
	[附属房间认购面积_累计],
	[主房间认购套数_累计],
	[附属房间认购套数_累计],

	/* 昨日签约 */
	Convert(decimal(18, 4),[签约金额_昨日]/10000.00) as [签约金额_昨日] ,
	Convert(decimal(18, 4),[主房间签约金额_昨日]/10000.00) as [主房间签约金额_昨日] ,
	Convert(decimal(18, 4),[附属房间签约金额_昨日]/10000.00) as [附属房间签约金额_昨日] ,
	Convert(decimal(18, 4),case when [主房间签约面积_昨日] =0 then [签约金额_昨日] else [签约金额_昨日]/[主房间签约面积_昨日] end) as [签约均价_昨日],
	[主房间签约面积_昨日],
	[附属房间签约面积_昨日],
	[主房间签约套数_昨日],
	[附属房间签约套数_昨日],
	/* 本日签约 */
	Convert(decimal(18, 4),[签约金额_本日]/10000.00) as [签约金额_本日] ,
	Convert(decimal(18, 4),[主房间签约金额_本日]/10000.00) as [主房间签约金额_本日] ,
	Convert(decimal(18, 4),[附属房间签约金额_本日]/10000.00) as [附属房间签约金额_本日] ,
	Convert(decimal(18, 4),case when [主房间签约面积_本日] =0 then [签约金额_本日] else [签约金额_本日]/[主房间签约面积_本日] end) as [签约均价_本日],
	[主房间签约面积_本日],
	[附属房间签约面积_本日],
	[主房间签约套数_本日],
	[附属房间签约套数_本日],
	/* 本周签约 */
	Convert(decimal(18, 4),[签约金额_本周]/10000.00) as [签约金额_本周] ,
	Convert(decimal(18, 4),[主房间签约金额_本周]/10000.00) as [主房间签约金额_本周] ,
	Convert(decimal(18, 4),[附属房间签约金额_本周]/10000.00) as [附属房间签约金额_本周] ,
	Convert(decimal(18, 4),case when [主房间签约面积_本周] =0 then [签约金额_本周] else [签约金额_本周]/[主房间签约面积_本周] end) as [签约均价_本周],
	[主房间签约面积_本周],
	[附属房间签约面积_本周],
	[主房间签约套数_本周],
	[附属房间签约套数_本周],
	/* 本月签约 */
	Convert(decimal(18, 4),[签约金额_本月]/10000.00) as [签约金额_本月] ,
	Convert(decimal(18, 4),[主房间签约金额_本月]/10000.00) as [主房间签约金额_本月] ,
	Convert(decimal(18, 4),[附属房间签约金额_本月]/10000.00) as [附属房间签约金额_本月] ,
	Convert(decimal(18, 4),case when [主房间签约面积_本月] =0 then [签约金额_本月] else [签约金额_本月]/[主房间签约面积_本月] end) as [签约均价_本月],
	[主房间签约面积_本月],
	[附属房间签约面积_本月],
	[主房间签约套数_本月],
	[附属房间签约套数_本月],
	/* 本季签约 */
	Convert(decimal(18, 4),[签约金额_本季]/10000.00) as [签约金额_本季] ,
	Convert(decimal(18, 4),[主房间签约金额_本季]/10000.00) as [主房间签约金额_本季] ,
	Convert(decimal(18, 4),[附属房间签约金额_本季]/10000.00) as [附属房间签约金额_本季] ,
	Convert(decimal(18, 4),case when [主房间签约面积_本季] =0 then [签约金额_本季] else [签约金额_本季]/[主房间签约面积_本季] end) as [签约均价_本季],
	[主房间签约面积_本季],
	[附属房间签约面积_本季],
	[主房间签约套数_本季],
	[附属房间签约套数_本季],
	/* 本年签约 */
	Convert(decimal(18, 4),[签约金额_本年]/10000.00) as [签约金额_本年] ,
	Convert(decimal(18, 4),[主房间签约金额_本年]/10000.00) as [主房间签约金额_本年] ,
	Convert(decimal(18, 4),[附属房间签约金额_本年]/10000.00) as [附属房间签约金额_本年] ,
	Convert(decimal(18, 4),case when [主房间签约面积_本年] =0 then [签约金额_本年] else [签约金额_本年]/[主房间签约面积_本年] end) as [签约均价_本年],
	[主房间签约面积_本年],
	[附属房间签约面积_本年],
	[主房间签约套数_本年],
	[附属房间签约套数_本年],
	/* 累计签约 */
	Convert(decimal(18, 4),[签约金额_累计]/10000.00) as [签约金额_累计] ,
	Convert(decimal(18, 4),[主房间签约金额_累计]/10000.00) as [主房间签约金额_累计] ,
	Convert(decimal(18, 4),[附属房间签约金额_累计]/10000.00) as [附属房间签约金额_累计] ,
	Convert(decimal(18, 4),case when [主房间签约面积_累计] =0 then [签约金额_累计] else [签约金额_累计]/[主房间签约面积_累计] end) as [签约均价_累计],
	[主房间签约面积_累计],
	[附属房间签约面积_累计],
	[主房间签约套数_累计],
	[附属房间签约套数_累计],
	[排序号],
	[名称],
	[项目编号],
	[父级名称],
	[父级项目编号],
	[公司名称],
	[公司编号]
from (
		 select 
				 /*三科需求*/
				 [签约套数_赠送车位昨日] ,
				[签约套数_赠送车位本日],
				 [签约套数_赠送车位本周],
				[签约套数_赠送车位本月],
				 [签约套数_赠送车位本季],
				[签约套数_赠送车位本年],
				[签约套数_赠送车位累计],
				
				[回款金额_车位昨日],
				[回款金额_住宅昨日],
				[回款金额_商业昨日],
				[回款金额_车位本日],
				[回款金额_住宅本日],
				[回款金额_商业本日],
				[回款金额_车位本周],
				[回款金额_住宅本周],
				[回款金额_商业本周],
				[回款金额_车位本月],
				[回款金额_住宅本月],
				[回款金额_商业本月],
				[回款金额_车位本季],
				[回款金额_住宅本季],
				[回款金额_商业本季],
				[回款金额_车位本年],
				[回款金额_住宅本年],
				[回款金额_商业本年],
				[回款金额_车位累计],
				[回款金额_住宅累计],
				[回款金额_商业累计],

				[认购套数_车位昨日],
				[认购套数_住宅昨日],
				[认购套数_商业昨日],
				[认购套数_车位本日],
				[认购套数_住宅本日],
				[认购套数_商业本日],
				[认购套数_车位本周],
				[认购套数_住宅本周],
				[认购套数_商业本周],
				[认购套数_车位本月],
				[认购套数_住宅本月],
				[认购套数_商业本月],
				[认购套数_车位本季],
				[认购套数_住宅本季],
				[认购套数_商业本季],
				[认购套数_车位本年],
				[认购套数_住宅本年],
				[认购套数_商业本年],
				[认购套数_车位累计],
				[认购套数_住宅累计],
				[认购套数_商业累计],

				[认购金额_车位昨日],
				[认购金额_住宅昨日],
				[认购金额_商业昨日],
				[认购金额_车位本日],
				[认购金额_住宅本日],
				[认购金额_商业本日],
				[认购金额_车位本周],
				[认购金额_住宅本周],
				[认购金额_商业本周],
				[认购金额_车位本月],
				[认购金额_住宅本月],
				[认购金额_商业本月],
				[认购金额_车位本季],
				[认购金额_住宅本季],
				[认购金额_商业本季],
				[认购金额_车位本年],
				[认购金额_住宅本年],
				[认购金额_商业本年],
				[认购金额_车位累计],
				[认购金额_住宅累计],
				[认购金额_商业累计],

				[签约套数_车位昨日],
				[签约套数_住宅昨日],
				[签约套数_商业昨日],
				[签约套数_车位本日],
				[签约套数_住宅本日],
				[签约套数_商业本日],
				[签约套数_车位本周],
				[签约套数_住宅本周],
				[签约套数_商业本周],
				[签约套数_车位本月],
				[签约套数_住宅本月],
				[签约套数_商业本月],
				[签约套数_车位本季],
				[签约套数_住宅本季],
				[签约套数_商业本季],
				[签约套数_车位本年],
				[签约套数_住宅本年],
				[签约套数_商业本年],
				[签约套数_车位累计],
				[签约套数_住宅累计],
				[签约套数_商业累计],

				[签约金额_车位昨日],
				[签约金额_住宅昨日],
				[签约金额_商业昨日],
				[签约金额_车位本日],
				[签约金额_住宅本日],
				[签约金额_商业本日],
				[签约金额_车位本周],
				[签约金额_住宅本周],
				[签约金额_商业本周],
				[签约金额_车位本月],
				[签约金额_住宅本月],
				[签约金额_商业本月],
				[签约金额_车位本季],
				[签约金额_住宅本季],
				[签约金额_商业本季],
				[签约金额_车位本年],
				[签约金额_住宅本年],
				[签约金额_商业本年],
				[签约金额_车位累计],
				[签约金额_住宅累计],
				[签约金额_商业累计],

				[贷款类回款金额_昨日],
				[非贷款类回款金额_昨日],
				[补充协议款_昨日],
				[回款金额_昨日],
				[楼款_模糊匹配_昨日],
				[首期_模糊匹配_昨日],
				[定金_模糊匹配_昨日],
				[其他_模糊匹配_昨日],

				[贷款类回款金额_本日],
				[非贷款类回款金额_本日],
				[补充协议款_本日],
				[回款金额_本日],
				[楼款_模糊匹配_本日],
				[首期_模糊匹配_本日],
				[定金_模糊匹配_本日],
				[其他_模糊匹配_本日],

				[贷款类回款金额_本周],
				[非贷款类回款金额_本周],
				[补充协议款_本周],
				[回款金额_本周],
				[楼款_模糊匹配_本周],
				[首期_模糊匹配_本周],
				[定金_模糊匹配_本周],
				[其他_模糊匹配_本周],

				[贷款类回款金额_本月],
				[非贷款类回款金额_本月],
				[补充协议款_本月],
				[回款金额_本月],
				[楼款_模糊匹配_本月],
				[首期_模糊匹配_本月],
				[定金_模糊匹配_本月],
				[其他_模糊匹配_本月],

				[贷款类回款金额_本季],
				[非贷款类回款金额_本季],
				[补充协议款_本季],
				[回款金额_本季],
				[楼款_模糊匹配_本季],
				[首期_模糊匹配_本季],
				[定金_模糊匹配_本季],
				[其他_模糊匹配_本季],

				[贷款类回款金额_本年],
				[非贷款类回款金额_本年],
				[补充协议款_本年],
				[回款金额_本年],
				[楼款_模糊匹配_本年],
				[首期_模糊匹配_本年],
				[定金_模糊匹配_本年],
				[其他_模糊匹配_本年],

				[贷款类回款金额_累计],
				[非贷款类回款金额_累计],
				[补充协议款_累计],
				[回款金额_累计],
				[楼款_模糊匹配_累计],
				[首期_模糊匹配_累计],
				[定金_模糊匹配_累计],
				[其他_模糊匹配_累计],
				
				[认购金额_昨日],
				[主房间认购金额_昨日],
				[附属房间认购金额_昨日],
				[主房间认购面积_昨日],
				[附属房间认购面积_昨日],
				[主房间认购套数_昨日],
				[附属房间认购套数_昨日],
				[认购金额_本日],
				[主房间认购金额_本日],
				[附属房间认购金额_本日],
				[主房间认购面积_本日],
				[附属房间认购面积_本日],
				[主房间认购套数_本日],
				[附属房间认购套数_本日],
				[认购金额_本周],
				[主房间认购金额_本周],
				[附属房间认购金额_本周],
				[主房间认购面积_本周],
				[附属房间认购面积_本周],
				[主房间认购套数_本周],
				[附属房间认购套数_本周],
				[认购金额_本月],
				[主房间认购金额_本月],
				[附属房间认购金额_本月],
				[主房间认购面积_本月],
				[附属房间认购面积_本月],
				[主房间认购套数_本月],
				[附属房间认购套数_本月],
				[认购金额_本季],
				[主房间认购金额_本季],
				[附属房间认购金额_本季],
				[主房间认购面积_本季],
				[附属房间认购面积_本季],
				[主房间认购套数_本季],
				[附属房间认购套数_本季],
				[认购金额_本年],
				[主房间认购金额_本年],
				[附属房间认购金额_本年],
				[主房间认购面积_本年],
				[附属房间认购面积_本年],
				[主房间认购套数_本年],
				[附属房间认购套数_本年],
				[认购金额_累计],
				[主房间认购金额_累计],
				[附属房间认购金额_累计],
				[主房间认购面积_累计],
				[附属房间认购面积_累计],
				[主房间认购套数_累计],
				[附属房间认购套数_累计],
				[签约金额_昨日],
				[主房间签约金额_昨日],
				[附属房间签约金额_昨日],
				[主房间签约面积_昨日],
				[附属房间签约面积_昨日],
				[主房间签约套数_昨日],
				[附属房间签约套数_昨日],
				[签约金额_本日],
				[主房间签约金额_本日],
				[附属房间签约金额_本日],
				[主房间签约面积_本日],
				[附属房间签约面积_本日],
				[主房间签约套数_本日],
				[附属房间签约套数_本日],
				[签约金额_本周],
				[主房间签约金额_本周],
				[附属房间签约金额_本周],
				[主房间签约面积_本周],
				[附属房间签约面积_本周],
				[主房间签约套数_本周],
				[附属房间签约套数_本周],
				[签约金额_本月],
				[主房间签约金额_本月],
				[附属房间签约金额_本月],
				[主房间签约面积_本月],
				[附属房间签约面积_本月],
				[主房间签约套数_本月],
				[附属房间签约套数_本月],
				[签约金额_本季],
				[主房间签约金额_本季],
				[附属房间签约金额_本季],
				[主房间签约面积_本季],
				[附属房间签约面积_本季],
				[主房间签约套数_本季],
				[附属房间签约套数_本季],
				[签约金额_本年],
				[主房间签约金额_本年],
				[附属房间签约金额_本年],
				[主房间签约面积_本年],
				[附属房间签约面积_本年],
				[主房间签约套数_本年],
				[附属房间签约套数_本年],
				[签约金额_累计],
				[主房间签约金额_累计],
				[附属房间签约金额_累计],
				[主房间签约面积_累计],
				[附属房间签约面积_累计],
				[主房间签约套数_累计],
				[附属房间签约套数_累计],
				[排序号],
				[名称],
				[GUID]   as [项目编号],
				[父级名称],
				[父级GUID] as [父级项目编号],
				[公司名称],
				[公司GUID] as [公司编号]
		 from detailResult
		 where 父级GUID <> 公司GUID
		 union all
		 select 
				 /*三科需求*/
				 isnull(sum(isnull([签约套数_赠送车位昨日],0)),0) ,
				isnull(sum(isnull([签约套数_赠送车位本日],0)),0),
				 isnull(sum(isnull([签约套数_赠送车位本周],0)),0),
				isnull(sum(isnull([签约套数_赠送车位本月],0)),0),
				 isnull(sum(isnull([签约套数_赠送车位本季],0)),0),
				isnull(sum(isnull([签约套数_赠送车位本年],0)),0),
				isnull(sum(isnull([签约套数_赠送车位累计],0)),0),
				
				isnull(sum(isnull([回款金额_车位昨日],0)),0),
				isnull(sum(isnull([回款金额_住宅昨日],0)),0),
				isnull(sum(isnull([回款金额_商业昨日],0)),0),
				isnull(sum(isnull([回款金额_车位本日],0)),0),
				isnull(sum(isnull([回款金额_住宅本日],0)),0),
				isnull(sum(isnull([回款金额_商业本日],0)),0),
				isnull(sum(isnull([回款金额_车位本周],0)),0),
				isnull(sum(isnull([回款金额_住宅本周],0)),0),
				isnull(sum(isnull([回款金额_商业本周],0)),0),
				isnull(sum(isnull([回款金额_车位本月],0)),0),
				isnull(sum(isnull([回款金额_住宅本月],0)),0),
				isnull(sum(isnull([回款金额_商业本月],0)),0),
				isnull(sum(isnull([回款金额_车位本季],0)),0),
				isnull(sum(isnull([回款金额_住宅本季],0)),0),
				isnull(sum(isnull([回款金额_商业本季],0)),0),
				isnull(sum(isnull([回款金额_车位本年],0)),0),
				isnull(sum(isnull([回款金额_住宅本年],0)),0),
				isnull(sum(isnull([回款金额_商业本年],0)),0),
				isnull(sum(isnull([回款金额_车位累计],0)),0),
				isnull(sum(isnull([回款金额_住宅累计],0)),0),
				isnull(sum(isnull([回款金额_商业累计],0)),0),

				isnull(sum(isnull([认购套数_车位昨日],0)),0),
				isnull(sum(isnull([认购套数_住宅昨日],0)),0),
				isnull(sum(isnull([认购套数_商业昨日],0)),0),
				isnull(sum(isnull([认购套数_车位本日],0)),0),
				isnull(sum(isnull([认购套数_住宅本日],0)),0),
				isnull(sum(isnull([认购套数_商业本日],0)),0),
				isnull(sum(isnull([认购套数_车位本周],0)),0),
				isnull(sum(isnull([认购套数_住宅本周],0)),0),
				isnull(sum(isnull([认购套数_商业本周],0)),0),
				isnull(sum(isnull([认购套数_车位本月],0)),0),
				isnull(sum(isnull([认购套数_住宅本月],0)),0),
				isnull(sum(isnull([认购套数_商业本月],0)),0),
				isnull(sum(isnull([认购套数_车位本季],0)),0),
				isnull(sum(isnull([认购套数_住宅本季],0)),0),
				isnull(sum(isnull([认购套数_商业本季],0)),0),
				isnull(sum(isnull([认购套数_车位本年],0)),0),
				isnull(sum(isnull([认购套数_住宅本年],0)),0),
				isnull(sum(isnull([认购套数_商业本年],0)),0),
				isnull(sum(isnull([认购套数_车位累计],0)),0),
				isnull(sum(isnull([认购套数_住宅累计],0)),0),
				isnull(sum(isnull([认购套数_商业累计],0)),0),

				isnull(sum(isnull([认购金额_车位昨日],0)),0),
				isnull(sum(isnull([认购金额_住宅昨日],0)),0),
				isnull(sum(isnull([认购金额_商业昨日],0)),0),
				isnull(sum(isnull([认购金额_车位本日],0)),0),
				isnull(sum(isnull([认购金额_住宅本日],0)),0),
				isnull(sum(isnull([认购金额_商业本日],0)),0),
				isnull(sum(isnull([认购金额_车位本周],0)),0),
				isnull(sum(isnull([认购金额_住宅本周],0)),0),
				isnull(sum(isnull([认购金额_商业本周],0)),0),
				isnull(sum(isnull([认购金额_车位本月],0)),0),
				isnull(sum(isnull([认购金额_住宅本月],0)),0),
				isnull(sum(isnull([认购金额_商业本月],0)),0),
				isnull(sum(isnull([认购金额_车位本季],0)),0),
				isnull(sum(isnull([认购金额_住宅本季],0)),0),
				isnull(sum(isnull([认购金额_商业本季],0)),0),
				isnull(sum(isnull([认购金额_车位本年],0)),0),
				isnull(sum(isnull([认购金额_住宅本年],0)),0),
				isnull(sum(isnull([认购金额_商业本年],0)),0),
				isnull(sum(isnull([认购金额_车位累计],0)),0),
				isnull(sum(isnull([认购金额_住宅累计],0)),0),
				isnull(sum(isnull([认购金额_商业累计],0)),0),

				isnull(sum(isnull([签约套数_车位昨日],0)),0),
				isnull(sum(isnull([签约套数_住宅昨日],0)),0),
				isnull(sum(isnull([签约套数_商业昨日],0)),0),
				isnull(sum(isnull([签约套数_车位本日],0)),0),
				isnull(sum(isnull([签约套数_住宅本日],0)),0),
				isnull(sum(isnull([签约套数_商业本日],0)),0),
				isnull(sum(isnull([签约套数_车位本周],0)),0),
				isnull(sum(isnull([签约套数_住宅本周],0)),0),
				isnull(sum(isnull([签约套数_商业本周],0)),0),
				isnull(sum(isnull([签约套数_车位本月],0)),0),
				isnull(sum(isnull([签约套数_住宅本月],0)),0),
				isnull(sum(isnull([签约套数_商业本月],0)),0),
				isnull(sum(isnull([签约套数_车位本季],0)),0),
				isnull(sum(isnull([签约套数_住宅本季],0)),0),
				isnull(sum(isnull([签约套数_商业本季],0)),0),
				isnull(sum(isnull([签约套数_车位本年],0)),0),
				isnull(sum(isnull([签约套数_住宅本年],0)),0),
				isnull(sum(isnull([签约套数_商业本年],0)),0),
				isnull(sum(isnull([签约套数_车位累计],0)),0),
				isnull(sum(isnull([签约套数_住宅累计],0)),0),
				isnull(sum(isnull([签约套数_商业累计],0)),0),

				isnull(sum(isnull([签约金额_车位昨日],0)),0),
				isnull(sum(isnull([签约金额_住宅昨日],0)),0),
				isnull(sum(isnull([签约金额_商业昨日],0)),0),
				isnull(sum(isnull([签约金额_车位本日],0)),0),
				isnull(sum(isnull([签约金额_住宅本日],0)),0),
				isnull(sum(isnull([签约金额_商业本日],0)),0),
				isnull(sum(isnull([签约金额_车位本周],0)),0),
				isnull(sum(isnull([签约金额_住宅本周],0)),0),
				isnull(sum(isnull([签约金额_商业本周],0)),0),
				isnull(sum(isnull([签约金额_车位本月],0)),0),
				isnull(sum(isnull([签约金额_住宅本月],0)),0),
				isnull(sum(isnull([签约金额_商业本月],0)),0),
				isnull(sum(isnull([签约金额_车位本季],0)),0),
				isnull(sum(isnull([签约金额_住宅本季],0)),0),
				isnull(sum(isnull([签约金额_商业本季],0)),0),
				isnull(sum(isnull([签约金额_车位本年],0)),0),
				isnull(sum(isnull([签约金额_住宅本年],0)),0),
				isnull(sum(isnull([签约金额_商业本年],0)),0),
				isnull(sum(isnull([签约金额_车位累计],0)),0),
				isnull(sum(isnull([签约金额_住宅累计],0)),0),
				isnull(sum(isnull([签约金额_商业累计],0)),0),				
				
				isnull(sum(isnull(贷款类回款金额_昨日, 0)), 0)    as [贷款类回款金额_昨日],
				isnull(sum(isnull(非贷款类回款金额_昨日, 0)), 0)   as [非贷款类回款金额_昨日],
				isnull(sum(isnull(补充协议款_昨日, 0)), 0)      as 补充协议款_昨日,
				isnull(sum(isnull(回款金额_昨日, 0)), 0)       as 回款金额_昨日,
				isnull(sum(isnull([楼款_模糊匹配_昨日], 0)), 0)   as [楼款_模糊匹配_昨日],
				isnull(sum(isnull([首期_模糊匹配_昨日], 0)), 0)   as [首期_模糊匹配_昨日],
				isnull(sum(isnull([定金_模糊匹配_昨日], 0)), 0)   as [定金_模糊匹配_昨日],
				isnull(sum(isnull([其他_模糊匹配_昨日], 0)), 0)   as [其他_模糊匹配_昨日],

				isnull(sum(isnull(贷款类回款金额_本日, 0)), 0)    as 贷款类回款金额_本日,
				isnull(sum(isnull(非贷款类回款金额_本日, 0)), 0)   as 非贷款类回款金额_本日,
				isnull(sum(isnull(补充协议款_本日, 0)), 0)      as 补充协议款_本日,
				isnull(sum(isnull(回款金额_本日, 0)), 0)       as 回款金额_本日,
				isnull(sum(isnull([楼款_模糊匹配_本日], 0)), 0)   as [楼款_模糊匹配_本日],
				isnull(sum(isnull([首期_模糊匹配_本日], 0)), 0)   as [首期_模糊匹配_本日],
				isnull(sum(isnull([定金_模糊匹配_本日], 0)), 0)   as [定金_模糊匹配_本日],
				isnull(sum(isnull([其他_模糊匹配_本日], 0)), 0)   as [其他_模糊匹配_本日],

				isnull(sum(isnull(贷款类回款金额_本周, 0)), 0)    as 贷款类回款金额_本周,
				isnull(sum(isnull(非贷款类回款金额_本周, 0)), 0)   as 非贷款类回款金额_本周,
				isnull(sum(isnull(补充协议款_本周, 0)), 0)      as 补充协议款_本周,
				isnull(sum(isnull(回款金额_本周, 0)), 0)       as 回款金额_本周,
				isnull(sum(isnull([楼款_模糊匹配_本周], 0)), 0)   as [楼款_模糊匹配_本周],
				isnull(sum(isnull([首期_模糊匹配_本周], 0)), 0)   as [首期_模糊匹配_本周],
				isnull(sum(isnull([定金_模糊匹配_本周], 0)), 0)   as [定金_模糊匹配_本周],
				isnull(sum(isnull([其他_模糊匹配_本周], 0)), 0)   as [其他_模糊匹配_本周],

				isnull(sum(isnull(贷款类回款金额_本月, 0)), 0)    as 贷款类回款金额_本月,
				isnull(sum(isnull(非贷款类回款金额_本月, 0)), 0)   as 非贷款类回款金额_本月,
				isnull(sum(isnull(补充协议款_本月, 0)), 0)      as 补充协议款_本月,
				isnull(sum(isnull(回款金额_本月, 0)), 0)       as 回款金额_本月,
				isnull(sum(isnull([楼款_模糊匹配_本月], 0)), 0)   as [楼款_模糊匹配_本月],
				isnull(sum(isnull([首期_模糊匹配_本月], 0)), 0)   as [首期_模糊匹配_本月],
				isnull(sum(isnull([定金_模糊匹配_本月], 0)), 0)   as [定金_模糊匹配_本月],
				isnull(sum(isnull([其他_模糊匹配_本月], 0)), 0)   as [其他_模糊匹配_本月],

				isnull(sum(isnull(贷款类回款金额_本季, 0)), 0)    as 贷款类回款金额_本季,
				isnull(sum(isnull(非贷款类回款金额_本季, 0)), 0)   as 非贷款类回款金额_本季,
				isnull(sum(isnull(补充协议款_本季, 0)), 0)      as 补充协议款_本季,
				isnull(sum(isnull(回款金额_本季, 0)), 0)       as 回款金额_本季,
				isnull(sum(isnull([楼款_模糊匹配_本季], 0)), 0)   as [楼款_模糊匹配_本季],
				isnull(sum(isnull([首期_模糊匹配_本季], 0)), 0)   as [首期_模糊匹配_本季],
				isnull(sum(isnull([定金_模糊匹配_本季], 0)), 0)   as [定金_模糊匹配_本季],
				isnull(sum(isnull([其他_模糊匹配_本季], 0)), 0)   as [其他_模糊匹配_本季],

				isnull(sum(isnull(贷款类回款金额_本年, 0)), 0)    as 贷款类回款金额_本年,
				isnull(sum(isnull(非贷款类回款金额_本年, 0)), 0)   as 非贷款类回款金额_本年,
				isnull(sum(isnull(补充协议款_本年, 0)), 0)      as 补充协议款_本年,
				isnull(sum(isnull(回款金额_本年, 0)), 0)       as 回款金额_本年,
				isnull(sum(isnull([楼款_模糊匹配_本年], 0)), 0)   as [楼款_模糊匹配_本年],
				isnull(sum(isnull([首期_模糊匹配_本年], 0)), 0)   as [首期_模糊匹配_本年],
				isnull(sum(isnull([定金_模糊匹配_本年], 0)), 0)   as [定金_模糊匹配_本年],
				isnull(sum(isnull([其他_模糊匹配_本年], 0)), 0)   as [其他_模糊匹配_本年],

				isnull(sum(isnull(贷款类回款金额_累计, 0)), 0)    as 贷款类回款金额_累计,
				isnull(sum(isnull(非贷款类回款金额_累计, 0)), 0)   as 非贷款类回款金额_累计,
				isnull(sum(isnull(补充协议款_累计, 0)), 0)      as 补充协议款_累计,
				isnull(sum(isnull(回款金额_累计, 0)), 0)       as 回款金额_累计,
				isnull(sum(isnull([楼款_模糊匹配_累计], 0)), 0)   as [楼款_模糊匹配_累计],
				isnull(sum(isnull([首期_模糊匹配_累计], 0)), 0)   as [首期_模糊匹配_累计],
				isnull(sum(isnull([定金_模糊匹配_累计], 0)), 0)   as [定金_模糊匹配_累计],
				isnull(sum(isnull([其他_模糊匹配_累计], 0)), 0)   as [其他_模糊匹配_累计],

				isnull(sum(isnull([认购金额_昨日], 0)), 0),
				isnull(sum(isnull([主房间认购金额_昨日], 0)), 0),
				isnull(sum(isnull([附属房间认购金额_昨日], 0)), 0),
				isnull(sum(isnull([主房间认购面积_昨日], 0)), 0),
				isnull(sum(isnull([附属房间认购面积_昨日], 0)), 0),
				isnull(sum(isnull([主房间认购套数_昨日], 0)), 0),
				isnull(sum(isnull([附属房间认购套数_昨日], 0)), 0),
				isnull(sum(isnull([认购金额_本日], 0)), 0),
				isnull(sum(isnull([主房间认购金额_本日], 0)), 0),
				isnull(sum(isnull([附属房间认购金额_本日], 0)), 0),
				isnull(sum(isnull([主房间认购面积_本日], 0)), 0),
				isnull(sum(isnull([附属房间认购面积_本日], 0)), 0),
				isnull(sum(isnull([主房间认购套数_本日], 0)), 0),
				isnull(sum(isnull([附属房间认购套数_本日], 0)), 0),
				isnull(sum(isnull([认购金额_本周], 0)), 0),
				isnull(sum(isnull([主房间认购金额_本周], 0)), 0),
				isnull(sum(isnull([附属房间认购金额_本周], 0)), 0),
				isnull(sum(isnull([主房间认购面积_本周], 0)), 0),
				isnull(sum(isnull([附属房间认购面积_本周], 0)), 0),
				isnull(sum(isnull([主房间认购套数_本周], 0)), 0),
				isnull(sum(isnull([附属房间认购套数_本周], 0)), 0),
				isnull(sum(isnull([认购金额_本月], 0)), 0),
				isnull(sum(isnull([主房间认购金额_本月], 0)), 0),
				isnull(sum(isnull([附属房间认购金额_本月], 0)), 0),
				isnull(sum(isnull([主房间认购面积_本月], 0)), 0),
				isnull(sum(isnull([附属房间认购面积_本月], 0)), 0),
				isnull(sum(isnull([主房间认购套数_本月], 0)), 0),
				isnull(sum(isnull([附属房间认购套数_本月], 0)), 0),
				isnull(sum(isnull([认购金额_本季], 0)), 0),
				isnull(sum(isnull([主房间认购金额_本季], 0)), 0),
				isnull(sum(isnull([附属房间认购金额_本季], 0)), 0),
				isnull(sum(isnull([主房间认购面积_本季], 0)), 0),
				isnull(sum(isnull([附属房间认购面积_本季], 0)), 0),
				isnull(sum(isnull([主房间认购套数_本季], 0)), 0),
				isnull(sum(isnull([附属房间认购套数_本季], 0)), 0),
				isnull(sum(isnull([认购金额_本年], 0)), 0),
				isnull(sum(isnull([主房间认购金额_本年], 0)), 0),
				isnull(sum(isnull([附属房间认购金额_本年], 0)), 0),
				isnull(sum(isnull([主房间认购面积_本年], 0)), 0),
				isnull(sum(isnull([附属房间认购面积_本年], 0)), 0),
				isnull(sum(isnull([主房间认购套数_本年], 0)), 0),
				isnull(sum(isnull([附属房间认购套数_本年], 0)), 0),
				isnull(sum(isnull([认购金额_累计], 0)), 0),
				isnull(sum(isnull([主房间认购金额_累计], 0)), 0),
				isnull(sum(isnull([附属房间认购金额_累计], 0)), 0),
				isnull(sum(isnull([主房间认购面积_累计], 0)), 0),
				isnull(sum(isnull([附属房间认购面积_累计], 0)), 0),
				isnull(sum(isnull([主房间认购套数_累计], 0)), 0),
				isnull(sum(isnull([附属房间认购套数_累计], 0)), 0),
				isnull(sum(isnull([签约金额_昨日], 0)), 0),
				isnull(sum(isnull([主房间签约金额_昨日], 0)), 0),
				isnull(sum(isnull([附属房间签约金额_昨日], 0)), 0),
				isnull(sum(isnull([主房间签约面积_昨日], 0)), 0),
				isnull(sum(isnull([附属房间签约面积_昨日], 0)), 0),
				isnull(sum(isnull([主房间签约套数_昨日], 0)), 0),
				isnull(sum(isnull([附属房间签约套数_昨日], 0)), 0),
				isnull(sum(isnull([签约金额_本日], 0)), 0),
				isnull(sum(isnull([主房间签约金额_本日], 0)), 0),
				isnull(sum(isnull([附属房间签约金额_本日], 0)), 0),
				isnull(sum(isnull([主房间签约面积_本日], 0)), 0),
				isnull(sum(isnull([附属房间签约面积_本日], 0)), 0),
				isnull(sum(isnull([主房间签约套数_本日], 0)), 0),
				isnull(sum(isnull([附属房间签约套数_本日], 0)), 0),
				isnull(sum(isnull([签约金额_本周], 0)), 0),
				isnull(sum(isnull([主房间签约金额_本周], 0)), 0),
				isnull(sum(isnull([附属房间签约金额_本周], 0)), 0),
				isnull(sum(isnull([主房间签约面积_本周], 0)), 0),
				isnull(sum(isnull([附属房间签约面积_本周], 0)), 0),
				isnull(sum(isnull([主房间签约套数_本周], 0)), 0),
				isnull(sum(isnull([附属房间签约套数_本周], 0)), 0),
				isnull(sum(isnull([签约金额_本月], 0)), 0),
				isnull(sum(isnull([主房间签约金额_本月], 0)), 0),
				isnull(sum(isnull([附属房间签约金额_本月], 0)), 0),
				isnull(sum(isnull([主房间签约面积_本月], 0)), 0),
				isnull(sum(isnull([附属房间签约面积_本月], 0)), 0),
				isnull(sum(isnull([主房间签约套数_本月], 0)), 0),
				isnull(sum(isnull([附属房间签约套数_本月], 0)), 0),
				isnull(sum(isnull([签约金额_本季], 0)), 0),
				isnull(sum(isnull([主房间签约金额_本季], 0)), 0),
				isnull(sum(isnull([附属房间签约金额_本季], 0)), 0),
				isnull(sum(isnull([主房间签约面积_本季], 0)), 0),
				isnull(sum(isnull([附属房间签约面积_本季], 0)), 0),
				isnull(sum(isnull([主房间签约套数_本季], 0)), 0),
				isnull(sum(isnull([附属房间签约套数_本季], 0)), 0),
				isnull(sum(isnull([签约金额_本年], 0)), 0),
				isnull(sum(isnull([主房间签约金额_本年], 0)), 0),
				isnull(sum(isnull([附属房间签约金额_本年], 0)), 0),
				isnull(sum(isnull([主房间签约面积_本年], 0)), 0),
				isnull(sum(isnull([附属房间签约面积_本年], 0)), 0),
				isnull(sum(isnull([主房间签约套数_本年], 0)), 0),
				isnull(sum(isnull([附属房间签约套数_本年], 0)), 0),
				isnull(sum(isnull([签约金额_累计], 0)), 0),
				isnull(sum(isnull([主房间签约金额_累计], 0)), 0),
				isnull(sum(isnull([附属房间签约金额_累计], 0)), 0),
				isnull(sum(isnull([主房间签约面积_累计], 0)), 0),
				isnull(sum(isnull([附属房间签约面积_累计], 0)), 0),
				isnull(sum(isnull([主房间签约套数_累计], 0)), 0),
				isnull(sum(isnull([附属房间签约套数_累计], 0)), 0),
				ParentHierarchyCode as [排序号],
				ParentProjName      as [名称],
				parentGuid          as [项目编号],
				[公司名称]              as [父级名称],
				BUGUID              as [父级项目编号],
				[公司名称]              as [公司名称],
				BUGUID              as [公司编号]
		 from detailResult
				  join proj on proj.parentGuid = detailResult.父级GUID and proj.projGuid = detailResult.GUID
			  --where parentGuid in (@projGUIDs)
		 group by proj.parentGUID, ParentHierarchyCode, ParentProjName, [公司名称], BUGUID
	 )A




S